# Autoimported language for mod insurgency

insurgency_Banned_For_Killing_Teammates=Du wirst vom Server gebannt, da du zu viele Teammitglieder getötet hast.
insurgency_CapturePoint_0=ALPHA
insurgency_CapturePoint_1=BRAVO
insurgency_CapturePoint_10=KILO
insurgency_CapturePoint_11=LIMA
insurgency_CapturePoint_12=MIKE
insurgency_CapturePoint_13=NOVEMBER
insurgency_CapturePoint_14=OSCAR
insurgency_CapturePoint_15=PAPA
insurgency_CapturePoint_2=CHARLIE
insurgency_CapturePoint_3=DELTA
insurgency_CapturePoint_4=ECHO
insurgency_CapturePoint_5=FOXTROT
insurgency_CapturePoint_6=GOLF
insurgency_CapturePoint_7=HOTEL
insurgency_CapturePoint_8=INDIA
insurgency_CapturePoint_9=JULIETT
insurgency_Compass_E=O
insurgency_Compass_E_Full=Osten
insurgency_Compass_N=N
insurgency_Compass_NE=NO
insurgency_Compass_NE_Full=Nord-Osten
insurgency_Compass_NW=NW
insurgency_Compass_NW_Full=Nord-Westen
insurgency_Compass_N_Full=Norden
insurgency_Compass_SE=SO
insurgency_Compass_SE_Full=Süd-Osten
insurgency_Compass_SW=SW
insurgency_Compass_SW_Full=Süd-Westen
insurgency_Compass_S_Full=Süden
insurgency_Compass_W=W
insurgency_Compass_W_Full=Westen
insurgency_GameUI_AutoBipod=Automatisch Zweibein aufstellen
insurgency_GameUI_Category_CoopModes=Kooperative Modi
insurgency_GameUI_Category_MultiplayerModes=Mehrspielermodi
insurgency_GameUI_Category_Tutorials=Tutorials
insurgency_GameUI_ChooseClassTeam=Team wechseln
insurgency_GameUI_Compete=Wettkampf
insurgency_GameUI_Controller_Disable=Controller deaktivieren
insurgency_GameUI_Controller_Enable=Controller aktivieren
insurgency_GameUI_Controller_NotFound=Keinen Controller gefunden
insurgency_GameUI_Coop=Kooperativ
insurgency_GameUI_CustomContent_Tag_CharacterSkin=Charakterskins
insurgency_GameUI_CustomContent_Tag_CustomUI=Benutzerdefiniertes UI
insurgency_GameUI_CustomContent_Tag_MapPack=Kartenpaket
insurgency_GameUI_CustomContent_Tag_Misc=Sonstiges
insurgency_GameUI_CustomContent_Tag_Playlist=Playlist 
insurgency_GameUI_CustomContent_Tag_SoundPack=Audiopaket
insurgency_GameUI_CustomContent_Tag_TotalConversion=Totale Umwandlung
insurgency_GameUI_CustomContent_Tag_WeaponSkin=Waffenskins
insurgency_GameUI_Day=Tag
insurgency_GameUI_Default=Standard
insurgency_GameUI_Facebook=Facebook
insurgency_GameUI_Filters=Filter
insurgency_GameUI_GameInstructor=Spielhinweise
insurgency_GameUI_GameSettingsConf=Spieleinstellungen
insurgency_GameUI_GameSettingsUseDefaults=Einstellungen zu den vorgeschlagenen Werten zurücksetzen?
insurgency_GameUI_Gamemode=Spielmodus
insurgency_GameUI_GamemodeDescription=Gefechtsregeln
insurgency_GameUI_Gamemodes=Spielmodi
insurgency_GameUI_GrenadeAutoSwitch=Granaten automatisch wechseln
insurgency_GameUI_Guides=Anleitungen
insurgency_GameUI_HQAnnouncer=HQ Ansager
insurgency_GameUI_HTMLMOTD=HTML MOTDs
insurgency_GameUI_Help=Hilfe
insurgency_GameUI_Icons_None=Nicht zugewiesen
insurgency_GameUI_JoinServer=>> Server beitreten
insurgency_GameUI_JoinServerFull=>> Server voll
insurgency_GameUI_Keyboard_Mouse=Maus und Tastatur
insurgency_GameUI_KillsSlashDeaths=Abschüsse / Tode
insurgency_GameUI_Main=Hauptmenü
insurgency_GameUI_MapCycle=Kartenrotation [%s1]
insurgency_GameUI_MapSelection=Kartenauswahl
insurgency_GameUI_ModMaking=Mod erstellen
insurgency_GameUI_ModifyKit=Kit anpassen
insurgency_GameUI_Mods=Mods
insurgency_GameUI_ModsDisabled=Mods: Deaktiviert
insurgency_GameUI_ModsEnabled=Mods: Aktiviert
insurgency_GameUI_Mods_Coop=Kooperative Mods
insurgency_GameUI_Mods_PVP=Mehrspieler Mods
insurgency_GameUI_Multiplayer=Mehrspieler
insurgency_GameUI_News=Neuigkeiten
insurgency_GameUI_Night=Nacht
insurgency_GameUI_Numbered=Nummeriert
insurgency_GameUI_Objectives=Ziele
insurgency_GameUI_OptionAnyStance=Beliebige Stellung
insurgency_GameUI_OptionProneAndCrouch=Bauchlage und hockend
insurgency_GameUI_OptionProneOnly=Nur Bauchlage
insurgency_GameUI_Options=Einstellungen
insurgency_GameUI_Profile=Profil
insurgency_GameUI_QuickConnect=Schnell verbinden >
insurgency_GameUI_Quickplay_ConnectingTo=Verbindung zu %s1 (%s2) herstellen ...
insurgency_GameUI_Quickplay_NoneFound=Keine Server gefunden, die den Filtern entsprechen
insurgency_GameUI_Quickplay_Searching=Suchen...
insurgency_GameUI_Quickplay_Searching2=Suchen... (%s1 Server gefunden)
insurgency_GameUI_RadialControlStyle=Schnellauswahlmenu
insurgency_GameUI_Refresh=Serverliste aktualisieren
insurgency_GameUI_Region=Region
insurgency_GameUI_RequestStatus_Completed=%s1 von %s2 passenden Filtern
insurgency_GameUI_RequestStatus_Requesting=%s1 von %s2 passenden Filtern
insurgency_GameUI_ResumeGame=Spiel fortsetzen
insurgency_GameUI_Rules=Regeln
insurgency_GameUI_Scrolling=Mausrad-Einstellung
insurgency_GameUI_SelectPlaylist=Playlist auswählen
insurgency_GameUI_ServerBrowser=Server Browser
insurgency_GameUI_ShotsFired=Schüsse abgefeuert
insurgency_GameUI_ShotsSlashMunitions=Schüsse / Munition
insurgency_GameUI_Solo=Allein
insurgency_GameUI_SquadOverview=Trupp Übersicht
insurgency_GameUI_StartGame=Spiel starten
insurgency_GameUI_Steam=Steam
insurgency_GameUI_SteamForums=Steam Forum
insurgency_GameUI_Training=Training
insurgency_GameUI_Translation=Übersetzung
insurgency_GameUI_Twitch=Twitch
insurgency_GameUI_Twitter=Twitter
insurgency_GameUI_UseOpensKit=Benutzen-Taste öffnet Kit
insurgency_GameUI_VacSecured=VAC gesichert
insurgency_GameUI_VipPreference=VIP Bevorzugung
insurgency_GameUI_Wiki=Wiki
insurgency_GameUI_Workshop=Workshop
insurgency_GameUI_YouTube=YouTube
insurgency_GameUI_coop_short=Ko-op
insurgency_GameUI_pvp_short=PVP
insurgency_GameUI_vote_botcount_checkpoint_0=10 Feinde pro Missionsziel
insurgency_GameUI_vote_botcount_checkpoint_1=15 Feinde pro Missionsziel
insurgency_GameUI_vote_botcount_checkpoint_2=20 Feinde pro Missionsziel
insurgency_GameUI_vote_botcount_checkpoint_3=Standard Gegneranzahl
insurgency_GameUI_vote_botcount_hunt_0=15 Feinde
insurgency_GameUI_vote_botcount_hunt_1=20 Feinde
insurgency_GameUI_vote_botcount_hunt_2=25 Feinde
insurgency_GameUI_vote_botcount_hunt_3=Standard Gegneranzahl
insurgency_GameUI_vote_botcount_outpost_0=Geringe Gegneranzahl
insurgency_GameUI_vote_botcount_outpost_1=Normale Gegneranzahl
insurgency_GameUI_vote_botcount_outpost_2=Hohe Gegneranzahl
insurgency_GameUI_vote_botcount_outpost_3=Sehr hohe Gegneranzahl
insurgency_GameUI_vote_changegamemode_ambush=Den Spielmodus zu Hinterhalt ändern?
insurgency_GameUI_vote_changegamemode_battle=Den Spielmodus zu Gefecht ändern?
insurgency_GameUI_vote_changegamemode_checkpoint=Den Spielmodus zu Kontrollpunkt ändern?
insurgency_GameUI_vote_changegamemode_conquest=Den Spielmodus zu Eroberung ändern?
insurgency_GameUI_vote_changegamemode_firefight=Den Spielmodus zu Feuergefecht ändern?
insurgency_GameUI_vote_changegamemode_flashpoint=Den Spielmodus zu Brennpunkt ändern?
insurgency_GameUI_vote_changegamemode_hunt=Den Spielmodus zu Jagd ändern?
insurgency_GameUI_vote_changegamemode_infiltrate=Den Spielmodus zu Infiltration ändern?
insurgency_GameUI_vote_changegamemode_invasion=Den Spielmodus zu Invasion ändern?
insurgency_GameUI_vote_changegamemode_occupy=Den Spielmodus zu Besetzen ändern?
insurgency_GameUI_vote_changegamemode_outpost=Den Spielmodus zu Außenposten ändern?
insurgency_GameUI_vote_changegamemode_searchdestroy=Den Spielmodus zu Suchen und Zerstören ändern?
insurgency_GameUI_vote_changegamemode_skirmish=Den Spielmodus zu Scharmützel ändern?
insurgency_GameUI_vote_changegamemode_strike=Zum Spielmodus \"Angriff\" wechseln?
insurgency_GameUI_vote_changegamemode_vendetta=Den Spielmodus zu Vendetta ändern?
insurgency_GameUI_vote_passed_change_ambush=Wechlse den Spielmodus zu Hinterhalt
insurgency_GameUI_vote_passed_change_battle=Wechsle den Spielmodus zu Gefecht
insurgency_GameUI_vote_passed_change_checkpoint=Wechsle den Spielmodus zu Kontrollpunkt
insurgency_GameUI_vote_passed_change_conquest=Wechsle den Spielmodus zu Eroberung
insurgency_GameUI_vote_passed_change_firefight=Wechsle den Spielmodus zu Feuergefecht
insurgency_GameUI_vote_passed_change_hunt=Wechsle den Spielmodus zu Jagd
insurgency_GameUI_vote_passed_change_infiltrate=Wechlse den Spielmodus zu Infiltration
insurgency_GameUI_vote_passed_change_invasion=Wechsle den Spielmodus zu Invasion
insurgency_GameUI_vote_passed_change_occupy=Wechsle den Spielmodus zu Besetzen
insurgency_GameUI_vote_passed_change_outpost=Wechsle den Spielmodus zu Außenposten
insurgency_GameUI_vote_passed_change_push=Wechsle den Spielmodus zu Vorstoß
insurgency_GameUI_vote_passed_change_searchdestroy=Wechsle den Spielmodus zu Suchen und Zerstören
insurgency_GameUI_vote_passed_change_skirmish=Wechlse den Spielmodus zu Scharmützel
insurgency_GameUI_vote_passed_change_vendetta=Wechsle den Spielmodus zu Vendetta
insurgency_Game_idle_kick=%s1 war zu lange untätig und wurde vom Server geworfen.
insurgency_Game_teammate_attack=%s1 hat ein Teammitglied angegriffen (%s2).
insurgency_Game_teammate_kills=Kameraden getötet: %s1 von %s2
insurgency_Hint_Attachments=Zubehör ausrüsten
insurgency_Hint_C4=C4 ausrüsten
insurgency_Hint_Flashlight=Taschenlampe ausrüsten
insurgency_Hint_Focus=Während dem Zielen: Fokussieren
insurgency_Hint_Frags=Splittergranate ausrüsten
insurgency_Hint_NV=Nachtsichtgerät ausrüsten
insurgency_Hint_Offline=Training (Offline)
insurgency_Hint_Online=Auftrag (Online)
insurgency_Hint_Plywood=Schießen Sie auf die Ziele durch das Sperrholz
insurgency_Hint_Primary=Primärwaffe ausrüsten
insurgency_Hint_ProtectVip=Den VIP beschützen!
insurgency_Hint_Slide=Während dem Sprinten: Rutschen
insurgency_Hint_ThrowC4=C4 werfen
insurgency_Hint_ThrowFrag=Splittergranate werfen
insurgency_Hint_ToggleCompass=Kompass ein-/ausschalten
insurgency_Hint_careful_around_teammates=Vorsicht!
insurgency_Hint_tk_punished=Für das Töten eines Teammitglieds bestraft!
insurgency_Hint_try_not_to_injure_teammates=Versuche Teammitglieder nicht zu verletzen.
insurgency_INS_end_round_stat_captures=%s2 nahm %s1 ein
insurgency_INS_end_round_stat_deaths=%s2 starb %s1
insurgency_INS_end_round_stat_hits=%s2 Treffer %s1
insurgency_INS_end_round_stat_kills=%s2 tötete %s1
insurgency_INS_end_round_stat_shots=%s2 Schüsse %s1
insurgency_KB_Attack=Angriff
insurgency_KB_ChangeInventory=Ausrüstung wechseln
insurgency_KB_ChangeSquad=Squad wechseln
insurgency_KB_ChangeStance=Haltung ändern
insurgency_KB_ChangeTeam=Team ändern / Scoreboard wechseln
insurgency_KB_Chat=Chat Nachricht
insurgency_KB_Combat=Kampf
insurgency_KB_Communications=Kommunikation
insurgency_KB_Compass=Kompass (halten)
insurgency_KB_CompassToggle=Kompass (umschalten)
insurgency_KB_Console=Konsole ein-/ausschalten
insurgency_KB_DisplayScoreBoard=Scoreboard anzeigen
insurgency_KB_DuckHold=Hocken (halten)
insurgency_KB_DuckToggle=Hocken (umschalten)
insurgency_KB_Firemode=Feuermodus ändern
insurgency_KB_Flashlight=Taschenlampe / Laser ein-/ ausschlaten
insurgency_KB_Focus=Fokussieren
insurgency_KB_Game=Spiel
insurgency_KB_Inventory=Inventar
insurgency_KB_Ironsights=Kimme und Korn
insurgency_KB_IronsightsHold=Zielen (halten)
insurgency_KB_IronsightsToggle=Zielen (umschalten)
insurgency_KB_Jump=Springen
insurgency_KB_LeanLeft=Nach links lehnen
insurgency_KB_LeanRight=Nach Rechts lehnen
insurgency_KB_Microphone=Mikrofon Aktivieren
insurgency_KB_Misc=Verschiedenes
insurgency_KB_MoveBack=Rückwärts bewegen
insurgency_KB_MoveForward=Vorwärts bewegen
insurgency_KB_MoveLeft=Nach Links bewegen
insurgency_KB_MoveRight=Nach Rechts bewegen
insurgency_KB_Movement=Bewegung
insurgency_KB_NextWeapon=Nächste Waffe
insurgency_KB_PrevWeapon=Vorherige Waffe
insurgency_KB_Prone=Hinlegen
insurgency_KB_Quit=Beenden
insurgency_KB_RadialMenu=Kreismenü
insurgency_KB_RadialMenuLeader=Kreismenü (Anführer)
insurgency_KB_RadialMenuOptions=Sprachbefehle
insurgency_KB_Reload=Nachladen
insurgency_KB_Screenshot=Screenshot aufnehmen
insurgency_KB_SecondaryFire=Sekundärer Feuermodus / Zweibein aufstellen
insurgency_KB_SecondaryGrenade=Garante werfen
insurgency_KB_SelEquipment=Ausrüstung wählen
insurgency_KB_SelKnife=Messer wählen
insurgency_KB_SelPrimary=Primärwaffe wählen
insurgency_KB_SelSecondary=Sekundärwaffe wählen
insurgency_KB_SelUnderbarrelWeapon=Unterlaufwaffe wählen
insurgency_KB_Spray=Logo  sprühen
insurgency_KB_Sprint=Sprinten
insurgency_KB_SprintFocusHold=Sprinten (halten) / Fokussieren
insurgency_KB_SprintFocusToggle=Sprinten (umschalten) / Fokussieren
insurgency_KB_TacticalMap=Taktische Karte
insurgency_KB_TeamChat=Team Nachricht
insurgency_KB_ToggleFloating=HUD anzeigen/ausschalten
insurgency_KB_TogglePrimarySecondary=Zwischen Primär-/Sekundärwaffe wechseln
insurgency_KB_ToggleRadialMenu=Kreismenü (umschalten)
insurgency_KB_ToggleRadialMenuLeader=Kreismenü (umschalten, Anführer)
insurgency_KB_Use=Benutzen / Waffe aufheben
insurgency_KB_UseAccessory=Spielerzubehör umschalten
insurgency_KB_UseReload=Nachladen / Item benutzen / Waffe aufheben
insurgency_KB_Walk=Gehen
insurgency_KB_WalkHold=Gehen (halten)
insurgency_KB_WalkToggle=Gehen (umschalten)
insurgency_Killed_Teammate=Du hast ein Teammitglied getötet!
insurgency_Msg_Captured=eingenommen
insurgency_Msg_Dominating=%s1 DOMINIERT
insurgency_Msg_FlagCapturedEnemy=haben unsere Informationen erobert
insurgency_Msg_FlagCapturedFriendly=eroberte die feindlichen Informationen
insurgency_Msg_FlagDroppedEnemy=haben die Informationen verloren
insurgency_Msg_FlagDroppedFriendly=hat die feindlichen Informationen verloren
insurgency_Msg_FlagReturnedEnemy=haben ihre Informationen zurückgebracht
insurgency_Msg_FlagReturnedFriendly=hat unsere Informationen zurückgebracht
insurgency_Msg_FlagTakenEnemy=hat die feindlichen Informationen gestohlen
insurgency_Msg_FlagTakenFriendly=hat unsere Informationen gestohlen
insurgency_Msg_Neutralized=neutralisiert
insurgency_Msg_ObjectDestroyed=Objekt zerstört
insurgency_Msg_ObjectDestroyedAt=Ziel zerstört
insurgency_Msg_ObjectiveWeaponCacheDestroyed=Waffenlager zerstört
insurgency_Msg_ObjectiveWithPrintName=%s1 [%s2]
insurgency_Msg_Revenge=%s1 nahm Rache an 
insurgency_SCHOOL_CP0_NAME=Schulhof
insurgency_endgamevote_extend=Wiederholen
insurgency_endgamevote_random=Zufällig
insurgency_endgamevote_shuffle=Aktualisieren
insurgency_endgamevote_title=Über die nächste Karte abstimmen
insurgency_game_description_battle=Das Ziel beider Teams ist es, sich vorwärts durch die Karte zu kämpfen. Ein Team gewinnt wenn es alle Ziele erobert hat.
insurgency_game_description_elimination=Im Suchen und Zerstören Modus muss das angreifende Team eines der beiden Lager der Verteidiger zerstören.
insurgency_game_description_firefight=Um zu gewinnen, muss dein Team alle Gebiete erobern oder das gegnerische Team eliminieren. Dein Team wird Verstärkung erhalten, sobald ein Gebiet erobert ist.
insurgency_game_description_infiltrate=Erlangen Sie die feindlichen Informationen und schützen Sie Ihre eigene Basis vor Infiltration. Ihr Team erhält eine Welle von Unterstützungen wenn feindliche Informationen gestohlen werden, oder ein gegnerischer Informationsträger getötet wird. Stellen Sie die feindlichen Informationen sicher, indem Sie sie zu Ihrer Basis bringen um den Sieg zu erlangen.
insurgency_game_description_short_ambush=Beschützen Sie den VIP vor gegnerischen Hinterhälten, während Sie ihn zum Extraktionspunkt eskortieren.
insurgency_game_description_skirmish=Kontrolliere alle Gebiete und zerstöre das feindliche Waffenversteck oder elimiere einfach alle vom gegnerischen Team.Jedes zurückeroberte Gebiet wird unverzüglich alle deine toten Teammitglieder wiederbeleben und mit einer zusätzliche Unterstützungswelle belohnt werden.Achtet darauf, euer eigenes Waffenversteck zu schützen. Sobald es zerstört ist, ist dein Team nicht mehr in Lage, zusätzliche Wellen durch Eroberungen zu erhalten,
insurgency_game_description_strike=Im Suchen und Zerstören Modus muss das angreifende Team alle Lager der Verteidiger zerstören.
insurgency_game_description_vendetta=Nehmen Sie den Kontrollpunkt ein oder eliminieren Sie das feindliche Team um zu gewinnen.
insurgency_game_gm_ambush=Hinterhalt
insurgency_game_gm_battle=Schlacht
insurgency_game_gm_checkpoint=Kontrollpunkt
insurgency_game_gm_conquer=Eroberung
insurgency_game_gm_elimination=Eliminierung
insurgency_game_gm_firefight=Feuergefecht
insurgency_game_gm_hunt=Jagd
insurgency_game_gm_infiltrate=Infiltration
insurgency_game_gm_invalid=Unbekannt
insurgency_game_gm_invasion=Invasion
insurgency_game_gm_occupy=Besetzung
insurgency_game_gm_outpost=Außenposten
insurgency_game_gm_push=Vorstoß
insurgency_game_gm_searchdestroy=Suchen und Zerstören
insurgency_game_gm_skirmish=Feuergefecht
insurgency_game_gm_strike=Angriff
insurgency_game_gm_survival=Überleben
insurgency_game_gm_training=Training
insurgency_game_gm_vendetta=Vergeltung
insurgency_game_push_attacking=Angreifen
insurgency_game_push_defending=Verteidigend
insurgency_game_team_winner=%s1 haben GEWONNEN!
insurgency_game_team_winner_obj_default=%s1 haben alle Ziele erfüllt
insurgency_playlist_conquer_coop=Eroberung
insurgency_playlist_conquer_coop_desc=Eroberung nur mit klassischen Einstellungen
insurgency_playlist_coop=Klassisch 
insurgency_playlist_elite_coop=Elite
insurgency_playlist_hardcore_coop=Hardcore
insurgency_playlist_pvp_sustained=Durchgehender Kampf
insurgency_prlobby_class=Klasse
insurgency_prlobby_kd=K:D
insurgency_prlobby_loser_spaced=N i e d e r l a g e
insurgency_prlobby_mission=Mission:
insurgency_prlobby_mvp=Wertvollster Spieler
insurgency_prlobby_roundswon_team1=Sicherheitskräfte:
insurgency_prlobby_roundswon_team2=Aufständische:
insurgency_prlobby_team1_stats=Sicherheitskräfte
insurgency_prlobby_team2_stats=Aufständische
insurgency_prlobby_winner_spaced=S i e g 
insurgency_prlobby_winner_spectate=%s1 hat gewonnen
insurgency_radial_affirmative=Bestätigt
insurgency_radial_area_hostile=Feindgebiet
insurgency_radial_cease_fire=Feuer einstellen
insurgency_radial_covering=Gebe Deckung
insurgency_radial_enemy_down=Feind eliminiert
insurgency_radial_flank_left=Flankiert links
insurgency_radial_flank_right=Flankiert rechts
insurgency_radial_get_ready=Bereitmachen
insurgency_radial_hold_position=Position halten
insurgency_radial_move_direction=Bewegt Euch
insurgency_radial_negative=Negativ
insurgency_radial_ontheway=Unterwegs
insurgency_radial_open_fire=Feuer eröffnen
insurgency_radial_report_status=Statusbericht
insurgency_radial_stick_together=Bleibt zusammen
insurgency_radial_switch_default=* Grundbefehle *
insurgency_radial_switch_leader=* Befehle für Anführer *
insurgency_radial_watch_area=Gebiet beobachten
insurgency_rp_alt_buhriz_coop=Buhriz
insurgency_rp_alt_contact_coop=Kontakt
insurgency_rp_alt_contact_hunt=Kontakt
insurgency_rp_alt_district_coop=Bezirk
insurgency_rp_alt_district_hunt=Bezirk
insurgency_rp_alt_district_survival=Bezirk
insurgency_rp_alt_heights_coop=Gebirge
insurgency_rp_alt_heights_hunt=Heights
insurgency_rp_alt_heights_outpost=Heights
insurgency_rp_alt_heights_survival=Heights
insurgency_rp_alt_market_coop=Market
insurgency_rp_alt_market_hunt=Market
insurgency_rp_alt_market_outpost=Market
insurgency_rp_alt_market_survival=Market
insurgency_rp_alt_ministry_coop=Ministry
insurgency_rp_alt_ministry_hunt=Ministry
insurgency_rp_alt_panj_hunt=Panj
insurgency_rp_alt_panj_outpost=Panj
insurgency_rp_alt_peak_coop=Peak
insurgency_rp_alt_peak_outpost=Peak
insurgency_rp_alt_revolt_coop=Revolt
insurgency_rp_alt_siege_coop=Siege
insurgency_rp_alt_sinjar_coop=Sinjar
insurgency_rp_alt_sinjar_survival=Sinjar
insurgency_rp_alt_tell_survival=Tell
insurgency_rp_alt_uprising_hunt=Uprising
insurgency_rp_alt_uprising_night=Uprising
insurgency_rp_alt_verticality_hunt=Verticality
insurgency_rp_alt_verticality_night=Verticality
insurgency_rp_alt_verticality_outpost=Verticality
insurgency_rp_alt_verticality_survival=Verticality
