# Autoimported language for mod insurgency

insurgency_Banned_For_Killing_Teammates=Você está sendo banido do servidor por matar muitos companheiros da equipa.
insurgency_Compass_E=E
insurgency_Compass_N=N
insurgency_GameUI_ChooseClassTeam=Mudar de equipa
insurgency_GameUI_Compete=Competir
insurgency_GameUI_Coop=Cooperativo
insurgency_GameUI_Help=Ajuda
insurgency_GameUI_Main=Principal
insurgency_GameUI_Multiplayer=Multijogador
insurgency_GameUI_News=Notícias
insurgency_GameUI_Options=Configurações
insurgency_GameUI_Profile=Perfil
insurgency_GameUI_ResumeGame=Voltar ao Jogo
insurgency_GameUI_ServerBrowser=Navegador de Servidores
insurgency_GameUI_Training=Treino
insurgency_GameUI_Translation=Tradução
insurgency_GameUI_Workshop=Oficina
insurgency_Game_idle_kick=%s1 esteve inactivo por muito tempo e foi Expulso.
insurgency_Game_teammate_kills=Mortes do Companheiro de Equipa %s1 de %s2
insurgency_Hint_Attachments=Equipar acessórios
insurgency_Hint_C4=Equipar C4
insurgency_Hint_Flashlight=Equipar lanterna
insurgency_Hint_Focus=Enquanto aponta: Focar
insurgency_Hint_Frags=Equipar granadas de fragmentação
insurgency_Hint_NV=Equipar visão noturna
insurgency_Hint_Offline=Praticar (Desconectado)
insurgency_Hint_Online=Missão (Conectado)
insurgency_Hint_Plywood=Atire em alvos através da madeira contraplacada
insurgency_Hint_Primary=Equipar arma primária
insurgency_Hint_ProtectVip=Proteja o VIP!
insurgency_Hint_Slide=Enquanto corre: Deslisar
insurgency_Hint_ThrowC4=Lançar C4
insurgency_Hint_ThrowFrag=Lançar Granada de Fragmentação
insurgency_Hint_ToggleCompass=Alternar Bússola
insurgency_Hint_careful_around_teammates=Cuidado!
insurgency_Hint_tk_punished=Punido por matar um colega de equipe!
insurgency_Hint_try_not_to_injure_teammates=Tente não ferir seus membros da equipa.
insurgency_INS_end_round_stat_captures=%s2 capturado %s1
insurgency_INS_end_round_stat_deaths=%s2 morreu %s1
insurgency_INS_end_round_stat_hits=%s2 acertar %s1
insurgency_INS_end_round_stat_kills=%s2 matou %s1
insurgency_INS_end_round_stat_shots=%s2 tiro %s1 
insurgency_KB_Attack=Atacar
insurgency_KB_ChangeInventory=Mudar Equipamento
insurgency_KB_ChangeSquad=Mudar de Esquadrão
insurgency_KB_ChangeStance=Mudar de posição
insurgency_KB_ChangeTeam=Mudar de Equipa / Alternar Placar
insurgency_KB_Chat=Mensagem de conversa
insurgency_KB_Combat=Combate
insurgency_KB_Communications=Comunicações
insurgency_KB_Compass=Bússola (manter premido)
insurgency_KB_CompassToggle=Bússola (alternar)
insurgency_KB_Console=Alternar consola
insurgency_KB_DisplayScoreBoard=Exibir Placar
insurgency_KB_DuckHold=Agachar (manter premido)
insurgency_KB_DuckToggle=Agachar (alternar)
insurgency_KB_Firemode=Mudar o ciclo do modo de fogo
insurgency_KB_Flashlight=Alternar Lanterna / Laser
insurgency_KB_Focus=Focar
insurgency_KB_Game=Jogo
insurgency_KB_Inventory=Inventório
insurgency_KB_Ironsights=Mira de ferro
insurgency_KB_IronsightsHold=Apontar (manter premido)
insurgency_KB_IronsightsToggle=Apontar (Alternar)
insurgency_KB_Jump=Saltar
insurgency_KB_LeanLeft=Inclinar para a Esquerda
insurgency_KB_LeanRight=Inclinar para a Direita
insurgency_KB_Microphone=Ativar Microfone
insurgency_KB_Misc=Diversos
insurgency_KB_MoveBack=Recuar
insurgency_KB_MoveForward=Siga em frente
insurgency_KB_MoveLeft=Mover para a Esquerda (Lateralmente)
insurgency_KB_MoveRight=Mover para a Direita (Lateralmente)
insurgency_KB_Movement=Movimento
insurgency_KB_NextWeapon=Próxima Arma
insurgency_KB_PrevWeapon=Arma anterior
insurgency_KB_Prone=Deitar
insurgency_KB_Quit=Sair
insurgency_KB_RadialMenu=Menu Radial
insurgency_KB_RadialMenuLeader=Menu radial (Líder)
insurgency_KB_RadialMenuOptions=Comandos de voz
insurgency_KB_Reload=Recarregar
insurgency_KB_Screenshot=Tirar captura de ecrã
insurgency_KB_SecondaryFire=Fogo Secundário / Implantar Bipé
insurgency_KB_SecondaryGrenade=Lançar granada
insurgency_KB_SelEquipment=Selecionar equipamento
insurgency_KB_SelKnife=Selecione Faca
insurgency_KB_SelPrimary=Selecione Arma Primária
insurgency_KB_SelSecondary=Selecione Arma Secundária
insurgency_KB_SelUnderbarrelWeapon=Selecionar arma de cano
insurgency_KB_Spray=Logotipo Pulverizador
insurgency_KB_Sprint=Correr
insurgency_KB_SprintFocusHold=Correr (manter premido) / Focar
insurgency_KB_SprintFocusToggle=Correr (Alternar) / Focar
insurgency_KB_TacticalMap=Mapa Táctico
insurgency_KB_TeamChat=Mensagem da Equipe
insurgency_KB_ToggleFloating=Alternar HUD Flutuante
insurgency_KB_TogglePrimarySecondary=Alternar primária / secundária
insurgency_KB_ToggleRadialMenu=Menu radial (alternar)
insurgency_KB_ToggleRadialMenuLeader=Menu Radial (alternar, líder)
insurgency_KB_Use=Usar Item / Pegar Arma
insurgency_KB_UseAccessory=Alternar Acessórios do Jogador
insurgency_KB_UseReload=Recarregar / Usar Item / Pegar arma
insurgency_KB_Walk=Andar
insurgency_KB_WalkHold=Andar (manter premido)
insurgency_KB_WalkToggle=Andar (alternar)
insurgency_Killed_Teammate=Mataste um colega de equipa!
insurgency_Msg_Captured=capturado
insurgency_Msg_Neutralized=neutralizado
insurgency_Msg_ObjectDestroyedAt=objectivo destruído 
insurgency_Msg_ObjectiveWeaponCacheDestroyed=provisões destruído
insurgency_game_gm_ambush=Emboscada
insurgency_game_gm_conquer=Conquistar
insurgency_game_gm_elimination=Eliminação
insurgency_game_gm_hunt=Caçada
insurgency_game_gm_infiltrate=Infiltrar
insurgency_game_gm_invalid=Desconhecido
insurgency_game_gm_invasion=Invasão
insurgency_game_gm_occupy=Ocupar
insurgency_game_gm_survival=Sobrevivência
insurgency_game_gm_training=Treino
insurgency_weapon_f1=F1 Granada
insurgency_weapon_f1_desc=Granada de Fragmentação Soviética
insurgency_weapon_m18=M18 Fumo
insurgency_weapon_m84=M84 Clarão
