# Autoimported language for mod insurgency

insurgency_CapturePoint_0=ALPHA
insurgency_CapturePoint_1=BRAVO
insurgency_CapturePoint_10=KILO
insurgency_CapturePoint_11=LIMA
insurgency_CapturePoint_12=MIKE
insurgency_CapturePoint_13=NOVEMBER
insurgency_CapturePoint_14=OSCAR
insurgency_CapturePoint_15=PAPA
insurgency_CapturePoint_2=CHARLIE
insurgency_CapturePoint_3=DELTA
insurgency_CapturePoint_4=ECHO
insurgency_CapturePoint_5=FOXTROT
insurgency_CapturePoint_6=GOLF
insurgency_CapturePoint_7=HOTEL
insurgency_CapturePoint_8=INDIA
insurgency_CapturePoint_9=JULIETT
insurgency_Compass_E=K
insurgency_Compass_E_Full=Kelet
insurgency_Compass_N=É
insurgency_Compass_NE=ÉK
insurgency_Compass_NE_Full=Északkelet
insurgency_Compass_NW=ÉNY
insurgency_Compass_NW_Full=Északnyugat
insurgency_Compass_N_Full=Észak
insurgency_Compass_S=D
insurgency_Compass_SE=DK
insurgency_Compass_SE_Full=Délkelet
insurgency_Compass_SW=DNY
insurgency_Compass_SW_Full=Délnyugat
insurgency_Compass_S_Full=Dél
insurgency_Compass_W=NY
insurgency_Compass_W_Full=Nyugat
insurgency_GameUI_AutoBipod=Fegyver automatikus letámasztása
insurgency_GameUI_Category_Tutorials=Útmutatók
insurgency_GameUI_ChooseClassTeam=Válassz csapatot!
insurgency_GameUI_Compete=Versengés
insurgency_GameUI_Coop=Kooperatív
insurgency_GameUI_CustomContent_Tag_CharacterSkin=Karakter kinézet
insurgency_GameUI_CustomContent_Tag_CustomTheater=Egyedi Hadszíntér
insurgency_GameUI_CustomContent_Tag_CustomUI=Egyedi Felhasználói Felület
insurgency_GameUI_CustomContent_Tag_MapPack=Pálya csomag
insurgency_GameUI_CustomContent_Tag_Misc=Egyéb
insurgency_GameUI_CustomContent_Tag_SoundPack=Hang csomag
insurgency_GameUI_CustomContent_Tag_TotalConversion=Teljes Átalakítás
insurgency_GameUI_CustomContent_Tag_WeaponSkin=Fegyver kinézet
insurgency_GameUI_Day=Nappal
insurgency_GameUI_Default=Alap
insurgency_GameUI_Facebook=Facebook
insurgency_GameUI_Filters=Szűrők
insurgency_GameUI_GameInstructor=Játék tippek
insurgency_GameUI_GameSettingsConf=Beállítások
insurgency_GameUI_GameSettingsUseDefaults=Beállítások visszaállítása az ajánlott értékekre?
insurgency_GameUI_Gamemode=Játékmód
insurgency_GameUI_GamemodeDescription=Fegyverhasználati Rendszabályok
insurgency_GameUI_Gamemodes=Játékmódok
insurgency_GameUI_GrenadeAutoSwitch=Automatikus Gránát-váltás
insurgency_GameUI_Guides=Útmutatók
insurgency_GameUI_HQAnnouncer=Bemondó
insurgency_GameUI_HTMLMOTD=HTML MOTD
insurgency_GameUI_Help=Segítség
insurgency_GameUI_Icons_None=Nincs hozzárendelve
insurgency_GameUI_KillsSlashDeaths=Ölés / Halál
insurgency_GameUI_Main=Főmenü
insurgency_GameUI_MapSelection=Pályaválasztás
insurgency_GameUI_ModMaking=Moddolás
insurgency_GameUI_ModifyKit=Felszerelés módosítása
insurgency_GameUI_Mods_Coop=Együttműködő Modok
insurgency_GameUI_Mods_PVP=Többjátékos Modok
insurgency_GameUI_Multiplayer=Többjátékos
insurgency_GameUI_News=Hírek
insurgency_GameUI_Night=Éjszaka
insurgency_GameUI_Numbered=Számozott
insurgency_GameUI_Objectives=Célpontok
insurgency_GameUI_OptionAnyStance=Bármilyen testhelyzet
insurgency_GameUI_OptionProneAndCrouch=Fekvés és Gugolás
insurgency_GameUI_OptionProneOnly=Csak fekvés
insurgency_GameUI_Options=Beállítások
insurgency_GameUI_Profile=Profil
insurgency_GameUI_Quickplay_ConnectingTo=Csatlakozás a következőhöz: %s1 (%s2)...
insurgency_GameUI_Quickplay_NoneFound=Nem található a keresési feltételeknek megfelelő szerver
insurgency_GameUI_Quickplay_Searching=Keresés...
insurgency_GameUI_Quickplay_Searching2=Keresés... (%s1 találat)
insurgency_GameUI_RadialControlStyle=Körmenü stílus
insurgency_GameUI_Refresh=Szerverek frissítése
insurgency_GameUI_Region=Terület
insurgency_GameUI_ResumeGame=Játék folytatása
insurgency_GameUI_Rules=Szabályok
insurgency_GameUI_Scrolling=Görgetés
insurgency_GameUI_ServerBrowser=Szerver böngésző
insurgency_GameUI_ShotsFired=Lövések
insurgency_GameUI_Solo=Egyszemélyes
insurgency_GameUI_SquadOverview=Osztag áttekintés
insurgency_GameUI_StartGame=Kezdés
insurgency_GameUI_Steam=Steam
insurgency_GameUI_SteamForums=Steam Fórumok
insurgency_GameUI_Training=Kiképzés
insurgency_GameUI_Translation=Fordítás
insurgency_GameUI_Twitch=Twitch
insurgency_GameUI_Twitter=Twitter
insurgency_GameUI_Wiki=Wiki
insurgency_GameUI_Workshop=Műhely
insurgency_GameUI_YouTube=YouTube
insurgency_GameUI_coop_short=Együttműködő
insurgency_GameUI_pvp_short=PVP
insurgency_GameUI_vote_botcount_checkpoint_0=10 Ellenség Feladatonként
insurgency_GameUI_vote_botcount_checkpoint_1=15 Ellenség Feladatonként
insurgency_GameUI_vote_botcount_checkpoint_2=20 Ellenség Feladatonként
insurgency_GameUI_vote_botcount_checkpoint_3=Ellenség Mennyisége: Alapértelmezett
insurgency_GameUI_vote_botcount_hunt_0=15 Ellenség
insurgency_GameUI_vote_botcount_hunt_1=20 Ellenség
insurgency_GameUI_vote_botcount_hunt_2=25 Ellenség
insurgency_GameUI_vote_botcount_hunt_3=Ellenség Mennyisége: Alapértelmezett
insurgency_GameUI_vote_botcount_outpost_0=Ellenség Mennyisége: Engedékeny
insurgency_GameUI_vote_botcount_outpost_1=Ellenség Mennyisége: Normális
insurgency_GameUI_vote_botcount_outpost_2=Ellenség Mennyisége: Könyörtelen
insurgency_GameUI_vote_botcount_outpost_3=Ellenség Mennyisége: Brutális
insurgency_Hint_ProtectVip=Védd meg a VIP-t!
insurgency_Hint_ToggleCompass=Iránytű ki/be
insurgency_Hint_careful_around_teammates=Óvatosan!
insurgency_KB_Attack=Támadás
insurgency_KB_ChangeInventory=Felszerelés módosítása
insurgency_KB_ChangeSquad=Osztag váltás
insurgency_KB_ChangeStance=Testhelyzet váltása
insurgency_KB_Chat=Chat üzenet
insurgency_KB_Combat=Harc
insurgency_KB_Communications=Kommunikáció
insurgency_KB_Console=Console ki/be
insurgency_KB_DuckHold=Guggolás (tart)
insurgency_KB_Firemode=Tűzelési mód váltás
insurgency_KB_Flashlight=Lámpa/Lézer ki/be
insurgency_KB_Focus=Fókuszálás
insurgency_KB_Game=Játék
insurgency_KB_Ironsights=Célirányzék
insurgency_KB_IronsightsHold=Célzás (tart)
insurgency_KB_IronsightsToggle=Célzás (ki/be)
insurgency_KB_Jump=Ugrás
insurgency_KB_Microphone=Mikrofon bekapcsolása
insurgency_KB_MoveBack=Hátra
insurgency_KB_MoveForward=Előre
insurgency_KB_MoveLeft=Balra
insurgency_KB_MoveRight=Jobbra
insurgency_KB_Movement=Mozgás
insurgency_KB_Prone=Kúszás
insurgency_KB_Quit=Kilépés
insurgency_KB_Reload=Újratöltés
insurgency_KB_Screenshot=Képernyőkép mentése
insurgency_KB_SecondaryFire=Másodlagos tűz/Fegyverállvány kitámasztása
insurgency_KB_SecondaryGrenade=Gránát hajítása
insurgency_KB_Sprint=Futás
insurgency_KB_SprintFocusHold=Sprint (tart) / Fókuszálás
insurgency_KB_TacticalMap=Taktikai térkép
insurgency_KB_TeamChat=Csapat üzenet
insurgency_KB_ToggleFloating=Lebegő HUD ki/be kapcsolása
insurgency_KB_Use=Tárgy használata/Fegyver felvétele
insurgency_KB_UseAccessory=Kiegészítő bekapcsolása
insurgency_KB_UseReload=Újratöltés/Tárgy használata/Fegyver felvétele
insurgency_KB_Walk=Sétálás
insurgency_KB_WalkHold=Séta (tart)
insurgency_Killed_Teammate=Megöltél egy csapattársat!
insurgency_Msg_Neutralized=Semlegesítve
insurgency_Msg_ObjectiveWithPrintName=%s1 [%s2]
insurgency_Msg_Revenge=%s1 bosszút állt rajta:
insurgency_Outpost_Objective=Védjétek az előörsöt és az ellátmányt bármi áron!
insurgency_UI_Loadout_Weight=Súly
insurgency_buhriz=Buhriz
insurgency_contact=Contact
insurgency_death_grenade_c4=C4
insurgency_death_grenade_m18=M18
insurgency_death_grenade_m84=M84
insurgency_death_prop_physics=PROP
insurgency_death_rocket_rpg7=RPG-7
insurgency_death_trigger_hurt=TRIGGER 
insurgency_district=District
insurgency_endgamevote_extend=Újrajátszás
insurgency_endgamevote_random=Véletlenszerű
insurgency_endgamevote_shuffle=Frissítés
insurgency_endgamevote_title=Szavazz a következő pályára!
insurgency_game_description_outpost=Védd az előörsödet és benne a fegyvertárat. A csapatod erősítést kap minden ellenséges támadás végén.
insurgency_game_description_short_outpost=Tartsd a területed ameddig lehet
insurgency_game_description_skirmish=Vegyétek uralmatok alá az összes célpontot és pusztítsátok el az ellenség raktárát vagy likvidáljátok az összes ellenséget.Amint elfoglaltok az ellenségtől egy célpontot az egész csapat újraéled és egy erősítési lehetőséggel gazdagodtok.Védjétek a raktárotokat, ha az ellenség a levegőbe repíti a csapatotok nem kap erősítési lehetőséget egy célpont elfoglalásával.
insurgency_game_description_training=Üdvözlünk az Insurgency-ben.Egy iraki, a harctértől távol lévő központba küldünk, hogy értékeljék tudásodat. Kövesd az oktatód utasításait, lehetőleg légy jó formában!
insurgency_game_gm_outpost=Előörs
insurgency_game_gt_invalid=Ismeretlen
insurgency_game_team_winner_eliminated_outpost=Túléltél ennyi szintet: %s2
insurgency_game_team_winner_obj_outpost=Túléltél ennyi szintet: %s2
insurgency_heights=Heights
insurgency_prlobby_average_life=Átlagos élettartam
insurgency_prlobby_casualties=Veszteségek
insurgency_prlobby_class=Szerep
insurgency_prlobby_kd=Ö:H
insurgency_prlobby_kills=Ölések
insurgency_prlobby_location=Helyszín:
insurgency_prlobby_loser_spaced=V e r e s é g
insurgency_prlobby_mission=Küldetés:
insurgency_prlobby_mvp=A Legértékesebb Játékos
insurgency_prlobby_obj=CPont
insurgency_prlobby_objectives=Célpontok
insurgency_prlobby_personal_stats=Személyes eredmények
insurgency_prlobby_preferred_class=Kedvelt szerep
insurgency_prlobby_preferred_class_none=Semmi
insurgency_prlobby_rounds_won=Megnyert körök
insurgency_prlobby_roundswon_team1=Biztonsági:
insurgency_prlobby_roundswon_team2=Felkelők:
insurgency_prlobby_score=Pontszám
insurgency_prlobby_team1_stats=Biztonsági
insurgency_prlobby_team2_stats=Felkelők
insurgency_prlobby_tie_spaced=D ö n t e t l e n
insurgency_prlobby_weapon_of_choice=Választott fegyver
insurgency_prlobby_winner_spaced=G y ő z e l e m
insurgency_radial_affirmative_subtitle=Értettem!
insurgency_radial_area_clear_subtitle=Tiszta a terep.
insurgency_radial_area_hostile_subtitle=Ellenséges körzet!
insurgency_radial_cease_fire_subtitle=Tüzet szüntess!
insurgency_radial_cover_me_subtitle=Fedezzetek.
insurgency_radial_covering_fire_subtitle=Fedezőtűzre van szükségem!
insurgency_radial_flank_left_subtitle=Kerüljünk balra.
insurgency_radial_flank_right_subtitle=Kerüljünk jobbra.
insurgency_radial_follow_me_subtitle=Kövessetek.
insurgency_radial_get_ready_subtitle=Felkészülni!
insurgency_radial_go_subtitle=Indulás!
insurgency_radial_hold_position=Tartsd az állást!
insurgency_radial_hold_position_subtitle=Tartsd az állást!
insurgency_radial_mark_enemy_subtitle=Ellenség!
insurgency_radial_mark_position_subtitle=Mozgás oda.
insurgency_radial_need_backup_subtitle=Segítségre van szükség!
insurgency_radial_negative_subtitle=Negatív.
insurgency_radial_ontheway_subtitle=Úton vagyok.
insurgency_radial_report_status=Helyzetjelentést
insurgency_radial_report_status_subtitle=Helyzetjelentést!
insurgency_radial_request_orders_subtitle=Parancsra várunk.
insurgency_radial_request_ordinance_subtitle=Tüzérségi zárótűzre van szükségünk.
insurgency_radial_spread_out_subtitle=Szétszóródni!
insurgency_radial_stick_together=Maradjunk együtt
insurgency_radial_stick_together_subtitle=Maradjunk együtt!
insurgency_radial_suppress_target_subtitle=Fedezőtüzet!
insurgency_radial_suppressing_target_subtitle=Tűz alá vettem Őket!
insurgency_radial_waypoint_leader_subtitle=Mozgás!
insurgency_revolt=Revolt
insurgency_rp_alt_buhriz_coop=Buhriz
insurgency_rp_alt_contact_coop=Contact
insurgency_rp_alt_contact_hunt=Contact
insurgency_rp_alt_district_coop=District
insurgency_rp_alt_district_hunt=District
insurgency_rp_alt_district_survival=District
insurgency_rp_alt_heights_coop=Heights
insurgency_rp_alt_heights_hunt=Heights
insurgency_rp_alt_heights_outpost=Heights
insurgency_rp_alt_heights_survival=Heights
insurgency_rp_alt_market_coop=Market
insurgency_rp_alt_market_hunt=Market
insurgency_rp_alt_market_outpost=Market
insurgency_rp_alt_market_survival=Market
insurgency_rp_alt_ministry_coop=Ministry
insurgency_rp_alt_ministry_hunt=Ministry
insurgency_rp_alt_panj_hunt=Panj
insurgency_rp_alt_panj_outpost=Panj
insurgency_rp_alt_peak_coop=Peak
insurgency_rp_alt_peak_outpost=Peak
insurgency_rp_alt_revolt_coop=Revolt
insurgency_rp_alt_siege_coop=Siege
insurgency_rp_alt_sinjar_coop=Sinjar
insurgency_rp_alt_sinjar_survival=Sinjar
insurgency_rp_alt_tell_survival=Tell
insurgency_rp_alt_uprising_hunt=Uprising
insurgency_rp_alt_uprising_night=Uprising
insurgency_rp_alt_verticality_hunt=Verticality
insurgency_rp_alt_verticality_night=Verticality
insurgency_rp_alt_verticality_outpost=Verticality
insurgency_rp_alt_verticality_survival=Verticality
insurgency_sinjar=Sinjar
insurgency_station=Station
insurgency_tell=Tell
insurgency_uprising=Uprising
insurgency_verticality=Verticality
insurgency_weapon_ak74=AK-74
insurgency_weapon_akm=AKM
insurgency_weapon_aks74u=AKS-74U
insurgency_weapon_anm14=AN-M14
insurgency_weapon_c4=C4
insurgency_weapon_c4_ied=IED
insurgency_weapon_fal=FAL
insurgency_weapon_galil=Galil
insurgency_weapon_galil_sar=Galil SAR
insurgency_weapon_gp25_he=GP-25 HE
insurgency_weapon_gurkha=Khukuri
insurgency_weapon_l1a1=L1A1 SLR
insurgency_weapon_m14=M14 EBR
insurgency_weapon_m16=M16A4
insurgency_weapon_m1911=M1911
insurgency_weapon_m1a1=M1 Carbine
insurgency_weapon_m203_he=M203 HE
insurgency_weapon_m249=M249
insurgency_weapon_m40a1=M40A1
insurgency_weapon_m45=M45A1
insurgency_weapon_m4a1=M4A1
insurgency_weapon_m590=M590
insurgency_weapon_m9=M9
insurgency_weapon_makarov=Makarov
insurgency_weapon_mini14=AC-556
insurgency_weapon_mk18=Mk18
insurgency_weapon_model10=Model 10
insurgency_weapon_mosin=Mosin
insurgency_weapon_mp40=MP40
insurgency_weapon_mp5=MP5K
insurgency_weapon_rpg7=RPG-7
insurgency_weapon_rpk=RPK
insurgency_weapon_sks=SKS
insurgency_weapon_sterling=Sterling
insurgency_weapon_toz=TOZ
insurgency_weapon_ump45=UMP-45
insurgency_weapon_upgrade_ap=AP lőszer
insurgency_weapon_upgrade_hp=HP lőszer
insurgency_weapon_upgrade_po4x24=PO 4x24
