# Autoimported language for mod insurgency

insurgency_Compass_E=E
insurgency_GameUI_ChooseClassTeam=Zmień drużynę
insurgency_GameUI_Coop=Kooperacja
insurgency_GameUI_GameSettingsConf=Ustawienia gry
insurgency_GameUI_GameSettingsUseDefaults=Zresetować ustawiania do rekomendowanych wartości?
insurgency_GameUI_Gamemode=Tryb gry
insurgency_GameUI_Help=Pomoc
insurgency_GameUI_Multiplayer=Gra wieloosobowa
insurgency_GameUI_News=Wiadomości
insurgency_GameUI_Options=Ustawienia
insurgency_GameUI_Profile=Profil
insurgency_GameUI_ResumeGame=Kontynuuj grę
insurgency_GameUI_ServerBrowser=Przeglądarka serwerów
insurgency_GameUI_Training=Trening
insurgency_GameUI_Workshop=Warsztat
insurgency_GameUI_vote_changegamemode_ambush=Zmienić tryb gry na ambush?
insurgency_GameUI_vote_changegamemode_infiltrate=Zmienić tryb gry na infiltrate?
insurgency_GameUI_vote_changegamemode_searchdestroy=Zmienić tryb gry na search and destroy?
insurgency_GameUI_vote_changegamemode_skirmish=Zmienić tryb gry na skirmish?
insurgency_GameUI_vote_changegamemode_strike=Zmienić tryb gry na strike?
insurgency_Game_teammate_attack=%s1 zaatakował członka drużyny (%s2).
insurgency_Hint_Offline=Trening (Offline)
insurgency_Hint_Online=Misja (Online)
insurgency_Hint_ProtectVip=Ochraniaj VIP-a!
insurgency_Hint_ToggleCompass=Pokaż Kompas
insurgency_Hint_tk_punished=Ukarany za zabicie członka drużyny!
insurgency_INS_end_round_stat_kills=%s2 zabił %s1
insurgency_KB_ChangeInventory=Zmień Wyposażenie
insurgency_KB_ChangeSquad=Zmień Oddział
insurgency_KB_ChangeTeam=Zmień Stronę / Tabela Wyników
insurgency_KB_Game=Gra
insurgency_Msg_Dominating=%s1 DOMINUJE
insurgency_rp_alt_buhriz_coop=Buhriz
insurgency_rp_alt_contact_coop=Contact
insurgency_rp_alt_heights_coop=Heights
