# Autoimported language for mod insurgency

insurgency_Compass_E=E
insurgency_Compass_N=N
insurgency_KB_Attack=Attacca
insurgency_KB_ChangeInventory=Cambia Kit
insurgency_KB_ChangeSquad=Cambia Squadrone
insurgency_KB_ChangeStance=Cambia Postura
insurgency_KB_ChangeTeam=Cambia Squadra/Guarda i Punteggi
insurgency_KB_Combat=Combatti
insurgency_KB_DuckHold=Accovacciati (tieni premuto)
insurgency_KB_DuckToggle=Accovacciati (singolo click)
insurgency_KB_Firemode=Cambia Tipo di Fuoco
insurgency_KB_Flashlight=Attiva/Disattiva Torcia / Laser
insurgency_KB_Focus=Focalizzati
insurgency_KB_IronsightsHold=Punta con l\'Ottica (tieni premuto)
insurgency_KB_IronsightsToggle=Punta con l\'Ottica (singolo click)
insurgency_KB_Jump=Salta
insurgency_KB_LeanLeft=Inclinati a Sinistra
insurgency_KB_LeanRight=Inclinati a Destra
insurgency_KB_Microphone=Attiva Microfono
insurgency_KB_MoveBack=Muoviti Indietro
insurgency_KB_MoveForward=Muoviti Avanti
insurgency_KB_MoveLeft=Muoviti a Sinistra
insurgency_KB_MoveRight=Muoviti a Destra
insurgency_KB_Movement=Movimento
insurgency_KB_Prone=Stenditi
insurgency_KB_Reload=Ricarica
insurgency_KB_SecondaryFire=Fuoco secondario / Usa Bipiede
insurgency_KB_Sprint=Corri
insurgency_KB_SprintFocusHold=Corri (tieni premuto)/Focalizzati
insurgency_KB_SprintFocusToggle=Corri (singolo click)/Focalizzati
insurgency_KB_TacticalMap=Mappa Tattica
insurgency_KB_ToggleFloating=Attiva/Disattiva HUD Fluttuante
insurgency_KB_Use=Usa Oggetto / Raccogli Arma
insurgency_KB_Walk=Cammina
insurgency_KB_WalkHold=Cammina (tieni premuto)
insurgency_KB_WalkToggle=Cammina (singolo click)
