# Autoimported language for mod insurgency

insurgency_Banned_For_Killing_Teammates=味方を殺しすぎた事によりサーバーからの接続を禁止されました。
insurgency_CapturePoint_0=アルファ
insurgency_CapturePoint_1=ブラボー
insurgency_CapturePoint_10=キロ
insurgency_CapturePoint_11=リマ
insurgency_CapturePoint_12=マイク
insurgency_CapturePoint_13=ノベンバー
insurgency_CapturePoint_14=オスカー
insurgency_CapturePoint_15=パパ
insurgency_CapturePoint_2=チャーリー
insurgency_CapturePoint_3=デルタ
insurgency_CapturePoint_4=エコー
insurgency_CapturePoint_5=フォックストロット
insurgency_CapturePoint_6=ゴルフ
insurgency_CapturePoint_7=ホテル
insurgency_CapturePoint_8=インディア
insurgency_CapturePoint_9=ジュリエット
insurgency_Compass_E=東
insurgency_Compass_N=北
insurgency_GameUI_AutoBipod=自動バイポッド展開
insurgency_GameUI_ChooseClassTeam=チーム変更
insurgency_GameUI_Compete=対戦
insurgency_GameUI_Coop=協力プレー
insurgency_GameUI_CustomContent_Tag_CharacterSkin=キャラクタースキン
insurgency_GameUI_CustomContent_Tag_CustomTheater=カスタムシアター
insurgency_GameUI_CustomContent_Tag_CustomUI=カスタム UI
insurgency_GameUI_CustomContent_Tag_MapPack=マップパック
insurgency_GameUI_CustomContent_Tag_Misc=その他
insurgency_GameUI_CustomContent_Tag_Playlist=プレイリスト
insurgency_GameUI_CustomContent_Tag_SoundPack=サウンドパック
insurgency_GameUI_CustomContent_Tag_TotalConversion=完全切り替え
insurgency_GameUI_CustomContent_Tag_WeaponSkin=武器スキン
insurgency_GameUI_GameInstructor=ゲーム内ヒント
insurgency_GameUI_GameSettingsConf=ゲーム設定
insurgency_GameUI_GameSettingsUseDefaults=お勧めの設定に戻しますか？
insurgency_GameUI_Gamemode=ゲームモード
insurgency_GameUI_GamemodeDescription=ゲームモードの説明
insurgency_GameUI_GrenadeAutoSwitch=グレネード自動切り替え
insurgency_GameUI_HQAnnouncer=HQ アナウンサー
insurgency_GameUI_HTMLMOTD=HTML MOTDs
insurgency_GameUI_Help=ヘルプ
insurgency_GameUI_Main=メイン
insurgency_GameUI_ModifyKit=キット編集
insurgency_GameUI_Multiplayer=マルチプレイヤー
insurgency_GameUI_News=情報
insurgency_GameUI_OptionAnyStance=全ての姿勢
insurgency_GameUI_OptionProneAndCrouch=匍匐としゃがみ
insurgency_GameUI_OptionProneOnly=匍匐のみ
insurgency_GameUI_Options=設定
insurgency_GameUI_Profile=プロフィール
insurgency_GameUI_ResumeGame=ゲームに戻る
insurgency_GameUI_ServerBrowser=サーバーブラウザー
insurgency_GameUI_SquadOverview=スクワッド一覧
insurgency_GameUI_Training=トレーニング
insurgency_GameUI_Translation=翻訳
insurgency_GameUI_VipPreference=VIP 優先度
insurgency_GameUI_Workshop=ワークショップ
insurgency_GameUI_vote_botcount_checkpoint_0=目標一つにつき敵１０人
insurgency_GameUI_vote_botcount_checkpoint_1=目標一つにつき敵１５人
insurgency_GameUI_vote_botcount_checkpoint_2=目標一つにつき敵２０人
insurgency_GameUI_vote_botcount_checkpoint_3=デフォルトの敵人数
insurgency_GameUI_vote_botcount_hunt_0=敵１５人
insurgency_GameUI_vote_botcount_hunt_1=敵２０人
insurgency_GameUI_vote_botcount_hunt_2=敵 ２５人
insurgency_GameUI_vote_botcount_hunt_3=デフォルトの敵人数
insurgency_GameUI_vote_botcount_outpost_0=少々の敵人数
insurgency_GameUI_vote_botcount_outpost_1=通常の敵人数
insurgency_GameUI_vote_botcount_outpost_2=多めの敵人数
insurgency_GameUI_vote_botcount_outpost_3=異常の敵人数
insurgency_GameUI_vote_changegamemode_ambush=ゲームモードをアンブッシュに切り替えますか？
insurgency_GameUI_vote_changegamemode_battle=ゲームモードをバトルに切り替えますか？
insurgency_GameUI_vote_changegamemode_checkpoint=ゲームモードをチェックポイントに切り替えますか？
insurgency_GameUI_vote_changegamemode_conquest=ゲームモードをコンクエストに切り替えますか？
insurgency_GameUI_vote_changegamemode_firefight=ゲームモードをファイアーファイトに切り替えますか？
insurgency_GameUI_vote_changegamemode_flashpoint=ゲームモードをフラッシュポイントに切り替えますか？
insurgency_GameUI_vote_changegamemode_hunt=ゲームモードをハントに切り替えますか？
insurgency_GameUI_vote_changegamemode_infiltrate=ゲームモードをインフィルトレイトに切り替えますか？
insurgency_GameUI_vote_changegamemode_invasion=ゲームモードをインベージョンに切り替えますか？
insurgency_GameUI_vote_changegamemode_occupy=ゲームモードをオキュパイに切り替えますか？
insurgency_GameUI_vote_changegamemode_outpost=ゲームモードをアウトポストに切り替えますか？
insurgency_GameUI_vote_changegamemode_push=ゲームモードをプッシュに切り替えますか？
insurgency_GameUI_vote_changegamemode_searchdestroy=ゲームモードをサーチアンドデストロイに切り替えますか？
insurgency_GameUI_vote_changegamemode_skirmish=ゲームモードをスカーミッシュに切り替えますか？
insurgency_GameUI_vote_changegamemode_strike=ゲームモードをストライクに切り替えますか？
insurgency_GameUI_vote_changegamemode_vendetta=ゲームモードをベンデタに切り替えますか？
insurgency_GameUI_vote_passed_change_ambush=ゲームモードをアンブッシュに切り替え中
insurgency_GameUI_vote_passed_change_battle=ゲームモードをバトルに切り替え中
insurgency_GameUI_vote_passed_change_checkpoint=ゲームモードをチェックポイントに切り替え中
insurgency_GameUI_vote_passed_change_conquest=ゲームモードをコンクエストに切り替え中
insurgency_GameUI_vote_passed_change_firefight=ゲームモードをファイアーファイトに切り替え中
insurgency_GameUI_vote_passed_change_flashpoint=ゲームモードをフラッシュポイントに切り替え中
insurgency_GameUI_vote_passed_change_hunt=ゲームモードをハントに切り替え中
insurgency_GameUI_vote_passed_change_infiltrate=ゲームモードをインフィルトレイトに切り替え中
insurgency_GameUI_vote_passed_change_invasion=ゲームモードをインベージョンに切り替え中
insurgency_GameUI_vote_passed_change_occupy=ゲームモードをオキュパイに切り替え中
insurgency_GameUI_vote_passed_change_outpost=ゲームモードをアウトポストに切り替え中
insurgency_GameUI_vote_passed_change_push=ゲームモードをプッシュに切り替え中
insurgency_GameUI_vote_passed_change_searchdestroy=ゲームモードをサーチアンドデストロイに切り替え中
insurgency_GameUI_vote_passed_change_skirmish=ゲームモードをスカーミッシュに切り替え中
insurgency_GameUI_vote_passed_change_strike=ゲームモードをストライクに切り替え中
insurgency_GameUI_vote_passed_change_vendetta=ゲームモードをベンデタに切り替え中
insurgency_Game_idle_kick=%s1 が長時間放置したためキックされました。
insurgency_Game_teammate_attack=%s1が仲間を攻撃した (%s2).
insurgency_Game_teammate_kills=チームキル: %s2中%s1
insurgency_Hint_Attachments=アタッチメントを装備する
insurgency_Hint_C4=C4爆弾を装備する
insurgency_Hint_Flashlight=フラッシュライトを装備する
insurgency_Hint_Focus=エイム中に:フォーカス
insurgency_Hint_Frags=手榴弾を装備する
insurgency_Hint_NV=ナイトヴィジョンを装備する
insurgency_Hint_Offline=練習(オフライン)
insurgency_Hint_Online=ミッション(オンライン)
insurgency_Hint_Plywood=薄い木を撃ち抜く
insurgency_Hint_Primary=プライマリー武器を装備
insurgency_Hint_ProtectVip=VIPを守れ！
insurgency_Hint_Slide=スプリント中に:スライド
insurgency_Hint_ThrowC4=C4爆弾を投げる
insurgency_Hint_ThrowFrag=手榴弾を投げる
insurgency_Hint_ToggleCompass=コンパスをトグル
insurgency_Hint_careful_around_teammates=気を付けろ！
insurgency_Hint_tk_punished=味方を殺したことにより罰を受けました！
insurgency_Hint_try_not_to_injure_teammates=味方を傷つけないようにしましょう。
insurgency_INS_end_round_stat_captures=%s2が%s1を確保した
insurgency_INS_end_round_stat_deaths=%s2死んだ%s1
insurgency_INS_end_round_stat_hits=%s2が%s1に命中させた
insurgency_INS_end_round_stat_kills=%s2が%s1を殺した
insurgency_INS_end_round_stat_shots=%s2が%s1を射撃した
insurgency_KB_Attack=攻撃
insurgency_KB_ChangeInventory=キット変更
insurgency_KB_ChangeSquad=スクワッド変更
insurgency_KB_ChangeStance=姿勢変更
insurgency_KB_Combat=戦闘
insurgency_KB_Communications=コミュニケーション
insurgency_KB_Compass=コンパス(長押し)
insurgency_KB_CompassToggle=コンパス(トグル)
insurgency_KB_Console=コンソールをトグル
insurgency_KB_DisplayScoreBoard=スコアボード表示
insurgency_KB_DuckHold=しゃがむ(長押し)
insurgency_KB_DuckToggle=しゃがむ(トグル)
insurgency_KB_Firemode=射撃モード変更
insurgency_KB_Flashlight=フラッシュライト/レーザーを点ける
insurgency_KB_Focus=集中
insurgency_KB_Game=ゲーム
insurgency_KB_Inventory=インベントリ
insurgency_KB_Ironsights=アイアンサイト
insurgency_KB_IronsightsHold=サイトをのぞき込む(ホールド)
insurgency_KB_IronsightsToggle=サイトをのぞき込む(トグル)
insurgency_KB_Jump=ジャンプ
insurgency_KB_LeanLeft=左にリーンする
insurgency_KB_LeanRight=右にリーンする
insurgency_KB_Misc=その他
insurgency_KB_MoveBack=後進
insurgency_KB_MoveForward=前進
insurgency_KB_MoveLeft=左に移動
insurgency_KB_MoveRight=右に移動
insurgency_KB_Movement=移動操作
insurgency_KB_NextWeapon=次の武器
insurgency_KB_PrevWeapon=前の武器
insurgency_KB_Prone=匍匐
insurgency_KB_Quit=終了
insurgency_KB_RadialMenu=ラジオコマンド
insurgency_KB_RadialMenuLeader=ラジオコマンド(リーダー)
insurgency_KB_RadialMenuOptions=ボイスコマンド
insurgency_KB_Reload=リロード
insurgency_KB_Screenshot=スクリーンショットを撮る
insurgency_KB_SecondaryFire=第二の射撃機能/バイポッドを展開
insurgency_KB_SecondaryGrenade=グレネードを軽く投げる
insurgency_KB_SelEquipment=装備を選択
insurgency_KB_SelKnife=ナイフを選択
insurgency_KB_SelPrimary=プライマリー武器を選択
insurgency_KB_SelSecondary=セカンダリー武器を選択
insurgency_KB_SelUnderbarrelWeapon=アンダーバレルに切り替え
insurgency_KB_Spray=ロゴをスプレー
insurgency_KB_Sprint=スプリント
insurgency_KB_SprintFocusHold=走る(長押し)/集中
insurgency_KB_SprintFocusToggle=走る(トグル)/集中
insurgency_KB_TacticalMap=マップ
insurgency_KB_TeamChat=チームメッセージ
insurgency_KB_TogglePrimarySecondary=プライマリー/セカンダリー武器をトグル
insurgency_KB_ToggleRadialMenu=ラジオコマンド(トグル)
insurgency_KB_ToggleRadialMenuLeader=ラジオコマンド(トグル、リーダー)
insurgency_KB_Use=アイテムの使用/武器を拾う
insurgency_KB_Walk=歩く
insurgency_KB_WalkHold=歩く(長押し)
insurgency_KB_WalkToggle=歩く(トグル)
insurgency_Killed_Teammate=見方を殺してしまいました！
insurgency_Msg_Captured=キャプチャーした
insurgency_Msg_Dominating=%s1がドミネートしています！
insurgency_Msg_Neutralized=無力化した
insurgency_Msg_ObjectiveWithPrintName=%s1 [%s2]
insurgency_game_push_attacking=攻撃中
insurgency_rp_alt_buhriz_coop=ブーリズ
insurgency_rp_alt_contact_coop=コンタクト
insurgency_rp_alt_contact_hunt=コンタクト
insurgency_rp_alt_district_coop=ディストリクト
insurgency_rp_alt_district_hunt=ディストリクト
insurgency_rp_alt_district_survival=ディストリクト
insurgency_rp_alt_heights_coop=ハイツ
insurgency_weapon_ak74=AK-47
insurgency_weapon_akm=AKM
insurgency_weapon_aks74u=AKS-74U
insurgency_weapon_anm14=AN-M14
insurgency_weapon_c4_ied=IED
insurgency_weapon_fal=FAL
insurgency_weapon_galil=Galil
insurgency_weapon_galil_sar=Galil SAR
insurgency_weapon_garand=M-1 GARAND
insurgency_weapon_gurkha=ククリ
insurgency_weapon_k98=K-98
insurgency_weapon_kabar=ナイフ
insurgency_weapon_l1a1=L1A1 SLR
insurgency_weapon_m14=M14 EBR
insurgency_weapon_m16=M16A4
insurgency_weapon_m1911=M1911
insurgency_weapon_m1a1=M1 Carbine
insurgency_weapon_m249=M249
insurgency_weapon_m40a1=M40A1
insurgency_weapon_m45=M45A1
insurgency_weapon_m4a1=M4A1
insurgency_weapon_m590=M590
insurgency_weapon_m9=M9
insurgency_weapon_makarov=Makarov
insurgency_weapon_mini14=AC-556
insurgency_weapon_mk18=Mk18
insurgency_weapon_model10=Model 10
insurgency_weapon_mosin=Mosin
insurgency_weapon_mp40=MP40
insurgency_weapon_mp5=MP5K
insurgency_weapon_rpg7=RPG-7
insurgency_weapon_rpk=RPK
insurgency_weapon_sks=SKS
insurgency_weapon_sterling=Sterling
insurgency_weapon_toz=TOZ
insurgency_weapon_ump45=UMP-45
