# Autoimported language for mod insurgency

insurgency_CapturePoint_0=Άλφα
insurgency_CapturePoint_2=Τσάρλι
insurgency_CapturePoint_3=Δέλτα
insurgency_CapturePoint_6=Γκόλφ
insurgency_Compass_E=Ε(ανατολικά)
insurgency_Compass_E_Full=Ανατολή
insurgency_Compass_NE=ΒΑ
insurgency_Compass_NE_Full=Βορειοανατολικά
insurgency_Compass_NW=ΒΔ
insurgency_Compass_NW_Full=Βορειοδυτικά
insurgency_Compass_N_Full=Βορράς
insurgency_Compass_SE_Full=Νοτιοανατολικά
insurgency_Compass_SW_Full=Νοτιοδυτικά
insurgency_Compass_S_Full=Νότος
insurgency_Compass_W_Full=Δύση
insurgency_Elimination_DestroyCache=Καταστρέψτε ένα εχθρικό απόθεμα πυρομαχικών!
insurgency_Elimination_ProtectCache=Προστατέψτε και τα δύο αποθέματα πυρομαχικών πάση θυσία!
insurgency_GameUI_AutoBipod=Αυτόματη παράταξη διπόδου
insurgency_GameUI_ChooseClassTeam=Αλλαγή ομάδας
insurgency_GameUI_Compete=Ανταγωνιστικό
insurgency_GameUI_CustomContent_Tag_MapPack=Πακέτο Χαρτών
insurgency_GameUI_CustomContent_Tag_Misc=Διάφορα
insurgency_GameUI_CustomContent_Tag_Playlist=Λίστα αναπαραγωγής
insurgency_GameUI_CustomContent_Tag_SoundPack=Πακέτο Ήχων
insurgency_GameUI_CustomContent_Tag_TotalConversion=Πλήρης Μετατροπή
insurgency_GameUI_Day=Ημέρα
insurgency_GameUI_Filters=Φίλτρα
insurgency_GameUI_GameInstructor=Συμβουλές κατα την διάρκεια του παιχνιδιού
insurgency_GameUI_GameSettingsConf=Ρυθμίσεις παιχνιδιού
insurgency_GameUI_GameSettingsUseDefaults=Επαναφορά στις αρχικές ρυθμίσεις;
insurgency_GameUI_Gamemode=Είδος παιχνιδιού
insurgency_GameUI_GamemodeDescription=Κανόνες εμπλοκής
insurgency_GameUI_Guides=Οδηγοί
insurgency_GameUI_HQAnnouncer=Εκφωνητής HQ
insurgency_GameUI_Help=Βοήθεια
insurgency_GameUI_KillsSlashDeaths=Φόνοι / Θάνατοι
insurgency_GameUI_Main=Κυρίως
insurgency_GameUI_MapSelection=Επιλογή Χάρτη
insurgency_GameUI_ModifyKit=Τροποποίηση εξοπλισμού
insurgency_GameUI_News=Νέα
insurgency_GameUI_Night=Νύχτα
insurgency_GameUI_Numbered=Αριθμημένο
insurgency_GameUI_Objectives=Στόχοι
insurgency_GameUI_OptionAnyStance=Οποιαδήποτε στάση
insurgency_GameUI_OptionProneOnly=Μόνο πρηνηδόν
insurgency_GameUI_Options=Ρυθμίσεις
insurgency_GameUI_Profile=Προφίλ
insurgency_GameUI_QuickConnect=Γρήγορη Σύνδεση >
insurgency_GameUI_Region=Περιοχή
insurgency_GameUI_ResumeGame=Συνέχεια Παιχνιδιού
insurgency_GameUI_Rules=Κανόνες
insurgency_GameUI_ServerBrowser=Αναζήτηση Εξυπηρετητή 
insurgency_GameUI_Solo=Μονό
insurgency_GameUI_SquadOverview=Προεπισκόπηση ομάδας
insurgency_GameUI_Training=Προπόνηση
insurgency_GameUI_Translation=Μετάφραση
insurgency_GameUI_VipPreference=Προτίμηση VIP
insurgency_GameUI_Workshop=Εργαστήρι
insurgency_GameUI_vote_botcount_checkpoint_0=10 εχθροί σε κάθε ΑΝΣΚ
insurgency_GameUI_vote_botcount_checkpoint_1=15 εχθροί σε κάθε ΑΝΣΚ
insurgency_GameUI_vote_botcount_checkpoint_2=20 εχθροί σε κάθε ΑΝΣΚ
insurgency_GameUI_vote_botcount_checkpoint_3=Προτεινόμενος αριθμός εχθρών
insurgency_GameUI_vote_botcount_hunt_0=15 εχθροί
insurgency_GameUI_vote_botcount_hunt_1=20 εχθροί
insurgency_GameUI_vote_botcount_hunt_2=25 εχθροί
insurgency_GameUI_vote_botcount_hunt_3=Προτεινόμενος αριθμός εχθρών
insurgency_GameUI_vote_botcount_outpost_0=Μικρός αριθμός εχθρών
insurgency_GameUI_vote_botcount_outpost_1=Κανονικός αριθμός εχθρών
insurgency_GameUI_vote_botcount_outpost_2=Μεγάλος αριθμός εχθρών
insurgency_GameUI_vote_botcount_outpost_3=Πολύ μεγάλος αριθμός εχθρών
insurgency_GameUI_vote_changegamemode_ambush=Αλλαγή είδους παιχνιδιού σε ambush;
insurgency_GameUI_vote_changegamemode_battle=Αλλαγή είδους παιχνιδιού σε battle;
insurgency_GameUI_vote_changegamemode_checkpoint=Αλλαγή είδους παιχνιδιού σε checkpoint;
insurgency_GameUI_vote_changegamemode_conquest=Αλλαγή είδους παιχνιδιού σε conquest;
insurgency_GameUI_vote_changegamemode_firefight=Αλλαγή είδους παιχνιδιού σε firefight;
insurgency_GameUI_vote_changegamemode_flashpoint=Αλλαγή είδους παιχνιδιού σε flashpoint;
insurgency_GameUI_vote_changegamemode_hunt=Αλλαγή είδους παιχνιδιού σε hunt;
insurgency_GameUI_vote_changegamemode_infiltrate=Αλλαγή είδους παιχνιδιού σε infiltrate;
insurgency_GameUI_vote_changegamemode_invasion=Αλλαγή είδους παιχνιδιού σε invasion;
insurgency_GameUI_vote_changegamemode_occupy=Αλλαγή είδους παιχνιδιού σε occupy;
insurgency_GameUI_vote_changegamemode_outpost=Αλλαγή είδους παιχνιδιού σε outpost;
insurgency_GameUI_vote_changegamemode_push=Αλλαγή είδους παιχνιδιού σε push;
insurgency_GameUI_vote_changegamemode_searchdestroy=Αλλαγή είδους παιχνιδιού σε search and destroy;
insurgency_GameUI_vote_changegamemode_skirmish=Αλλαγή είδους παιχνιδιού σε skirmish;
insurgency_GameUI_vote_changegamemode_strike=Αλλαγή είδους παιχνιδιού σε strike;
insurgency_GameUI_vote_changegamemode_vendetta=Αλλαγή είδους παιχνιδιού σε vendetta;
insurgency_GameUI_vote_passed_change_ambush=Αλλάζοντας του είδους παιχνιδιού σε ambush...
insurgency_GameUI_vote_passed_change_battle=Αλλάζοντας του είδους παιχνιδιού σε battle...
insurgency_GameUI_vote_passed_change_checkpoint=Αλλάζοντας του είδους παιχνιδιού σε checkpoint...
insurgency_GameUI_vote_passed_change_conquest=Αλλάζοντας του είδους παιχνιδιού σε conquest...
insurgency_GameUI_vote_passed_change_firefight=Αλλάζοντας του είδους παιχνιδιού σε firefight...
insurgency_GameUI_vote_passed_change_flashpoint=Αλλάζοντας του είδους παιχνιδιού σε flashpoint...
insurgency_GameUI_vote_passed_change_hunt=Αλλάζοντας του είδους παιχνιδιού σε hunt...
insurgency_GameUI_vote_passed_change_infiltrate=Αλλάζοντας του είδους παιχνιδιού σε infiltrate...
insurgency_GameUI_vote_passed_change_invasion=Αλλάζοντας του είδους παιχνιδιού σε invasion...
insurgency_GameUI_vote_passed_change_occupy=Αλλάζοντας του είδους παιχνιδιού σε occupy...
insurgency_GameUI_vote_passed_change_outpost=Αλλάζοντας του είδους παιχνιδιού σε outpost...
insurgency_GameUI_vote_passed_change_push=Αλλάζοντας του είδους παιχνιδιού σε push...
insurgency_GameUI_vote_passed_change_searchdestroy=Αλλάζοντας του είδους παιχνιδιού σε search and destroy...
insurgency_GameUI_vote_passed_change_skirmish=Αλλάζοντας του είδους παιχνιδιού σε skirmish...
insurgency_GameUI_vote_passed_change_strike=Αλλάζοντας του είδους παιχνιδιού σε strike...
insurgency_GameUI_vote_passed_change_vendetta=Αλλάζοντας του είδους παιχνιδιού σε vendetta...
insurgency_KB_Attack=Επίθεση
insurgency_KB_ChangeInventory=Αλλαγή εξοπλισμού
insurgency_KB_ChangeSquad=Αλλαγή διμοιρίας
insurgency_KB_ChangeStance=Αλλαγή Στάσης
insurgency_KB_ChangeTeam=Αλλαγή ομάδας / Εμφάνιση Πίνακα σκορ
insurgency_KB_Combat=Μάχη
insurgency_KB_DisplayScoreBoard=Εμφάνιση πίνακα βαθμολογίας
insurgency_KB_Focus=Συγκέντρωση
insurgency_KB_Game=Παιχνίδι
insurgency_KB_Inventory=Απόθεμα
insurgency_KB_Jump=Άλμα
insurgency_KB_Microphone=Ενεργοποιήστε το Μικρόφωνο
insurgency_KB_Movement=Κίνηση
insurgency_KB_NextWeapon=Επόμενο Όπλο
insurgency_KB_PrevWeapon=Προηγούμενο Όπλο
insurgency_KB_Prone=Πρηνηδόν
insurgency_KB_RadialMenuOptions=Φωνητικές Εντολές
insurgency_KB_SelEquipment=Επιλέξτε Εξοπλισμό
insurgency_KB_SelKnife=Επιλέξτε Μαχαίρι
insurgency_KB_SelPrimary=Επιλογή Βασικού Όπλου
insurgency_KB_SelSecondary=Επιλογή Δευτερεύοντος Όπλου
insurgency_KB_SelUnderbarrelWeapon=Επιλογή Όπλου Κάτωθεν Κάνης
insurgency_KB_Sprint=Γρήγορο τρέξιμο
insurgency_KB_SprintFocusHold=Γρήγορο τρέξιμο (κρατήστε) / Συγκέντρωση
insurgency_KB_SprintFocusToggle=Γρήγορο τρέξιμο (ενεργοποιήστε) / Συγκέντρωση
insurgency_KB_TogglePrimarySecondary=Εναλλαγή Βασικού/Δευτερεύοντος
insurgency_KB_Walk=Περπάτημα
insurgency_KB_WalkHold=Περπάτημα (κρατήστε)
insurgency_KB_WalkToggle=Περπάτημα (ενεργοποιήστε)
insurgency_Msg_ObjectiveWithPrintName=%s1 [%s2]
insurgency_Push_Fallback=Ο εχθρός προχωράει! Οπισθοχώρηση και ανασύνταξη!
insurgency_SECLeader_RoleName=Διμοιρίτης
insurgency_Spec_ChangeCamera=Αλλαγή Κάμερας
insurgency_Spec_NextPlayer=Επόμενος Παίκτης
insurgency_Spec_PreviousPlayer=Προηγούμενος Παίκτης
insurgency_Strike_DestroyCaches=Καταστρέψτε όλα τα εχθρικά αποθέματα πυρομαχικών!
insurgency_Strike_ProtectCaches=Προστατέψτε τα αποθέματα πυρομαχικών πάση θυσία!
insurgency_Team_Allies=Σύμμαχοι 
insurgency_Team_Axis=Άξωνας
insurgency_Team_Insurgent=Αντάρτες
insurgency_Team_Sec_NATOForces=Δυνάμεις ΝΑΤΟ
insurgency_Team_Sec_USMarines=Αμερικανοί Πεζονάυτες
insurgency_Team_Security=Δυνάμεις Ασφαλείας
insurgency_Team_Spectators=Θεατές
insurgency_UI_PlayerCount=ΠΑΙΚΤΕΣ 
insurgency_death_bayonet=ΞΙΦΟΛΟΓΧΗ 
insurgency_death_door=ΠΟΡΤΑ
insurgency_death_door_rotating=ΠΟΡΤΑ
insurgency_death_grenade_c4=C4
insurgency_death_grenade_m18=M18
insurgency_death_grenade_m84=M84
insurgency_death_rocket_rpg7=RPG-7
insurgency_endgamevote_extend=Επανάληψη 
insurgency_endgamevote_random=Τυχαίο
insurgency_endgamevote_shuffle=Ανανέωση
insurgency_game_begin_shorty=Το παιχνίδι θα ξεκινήσει σύντομα 
insurgency_game_description_short_outpost=Υπερασπιστείτε τη θέση σας για όσο το δυνατόν περισσότερο. 
insurgency_game_gm_training=Προπόνηση
insurgency_game_gt_invalid=Άγνωστο
insurgency_game_gt_normal=Κανονικό
insurgency_game_gt_realism=Ρεαλισμός
insurgency_game_next_round=ΕΠΟΜΕΝΟΣ ΓΥΡΟΣ
insurgency_game_restart_in_secs=Το παιχνίδι θα επαναληφθεί σε 1 sec
insurgency_game_scramble_in_sec=Ανακάτεμα των ομάδων !\n Το παιχνίδι θα επαναληφθεί σε 1 sec
insurgency_game_scramble_in_secs=Ανακάτεμα των ομάδων !\n Το παιχνίδι θα επαναληφθεί σε 1 sec
insurgency_game_scramble_onrestart=Αυτόματο ανακάτεμα των ομάδων!
insurgency_game_switch_in_sec=Αλλαγή ομάδων! \n Το παιχνίδι θα επαναληφθεί σε 1 sec
insurgency_game_switch_in_secs=Αλλαγή ομάδων! \n Το παιχνίδι θα επαναληφθεί σε 1 sec
insurgency_game_team_tie=ΙΣΟΠΑΛΙΑ!
insurgency_game_team_tie_timer=Λήξη χρόνου
insurgency_game_waiting_for_players=Αναμονή για παίχτες!
insurgency_gear_chest_carrier_desc=Επιπλέον πυρομαχικά και δύο δευτερεύοντα εκρηκτικά
insurgency_gear_chest_rig=Εξάρτηση
insurgency_gear_chest_rig_desc=Επιπλέον πυρομαχικά και ένα δευτερεύον εκρηκτικό 
insurgency_gear_heavy_armor=Βαρέως τύπου αλεξίσφαιρο γιλέκο
insurgency_gear_heavy_armor_desc=Βαρέως τύπου ενισχυμένο Kevlar γιλέκο
insurgency_gear_light_armor=Ελαφρύ αλεξίσφαιρο γιλέκο
insurgency_gear_light_armor_desc=Ένα βασικό γιλέκο Kevlar
insurgency_gear_nvg=NVG
insurgency_gear_slot_accessory=Αξεσουάρ 
insurgency_gear_slot_armor=θωράκηση
insurgency_gear_slot_vest=Γιλέκα μάχης
insurgency_hud_ammo_display=ΠΥΡΟΜΑΧΙΚΑ
insurgency_hud_mag_display=ΓΕΜΙΣΤΗΡΕΣ
insurgency_hud_round_display=ΣΦΑΙΡΕΣ
insurgency_ins_instr_explain_protect_vip=Προστάτευσε τον VIP
insurgency_inventory_main_category_3=Εκρηκτικά
insurgency_playlist_coop=Κλασικό 
insurgency_playlist_pvp_sustained_desc=Πολλές ενισχύσεις, για επική μάχη. 
insurgency_playlist_training=Προπόνηση
insurgency_prlobby_casualties=Απώλειες
insurgency_prlobby_class=Κλάση 
insurgency_prlobby_loser_spaced=Ή τ τ α 
insurgency_prlobby_mvp=Πολυτιμότερος Παίκτης
insurgency_prlobby_tie_spaced=Ι σ ο π α λ ί α 
insurgency_prlobby_winner_spaced=Ν ί κ η
insurgency_radial_affirmative_subtitle=Θετικό.
insurgency_radial_area_hostile_subtitle=Εχθρική Περιοχή!
insurgency_radial_cease_fire_subtitle=Παύσατε Πυρ!
insurgency_radial_negative_subtitle=Αρνητικό.
insurgency_round_restart_in_sec=Ο γύρος θα επαναληφθεί σε 1 sec
insurgency_round_restart_in_secs=Ο γύρος θα επαναληφθεί σε 1 sec
insurgency_rp_alt_buhriz_coop=Buhriz
insurgency_rp_alt_contact_coop=Contact
insurgency_rp_alt_contact_hunt=Contact
insurgency_rp_alt_district_coop=District
insurgency_rp_alt_district_hunt=District
insurgency_rp_alt_district_survival=District
insurgency_rp_alt_heights_coop=Heights
insurgency_scoreboard_category_name=ΠΑΙΚΤΗΣ
insurgency_scoreboard_category_obj=ΑΝΣΚ
insurgency_scoreboard_category_score=ΒΑΘΜΟΛΟΓΙΑ
insurgency_weapon_ak74=AK-74
insurgency_weapon_akm=AKM
insurgency_weapon_anm14=AN-M14
insurgency_weapon_at4=AT4
insurgency_weapon_c4=C4
insurgency_weapon_c4_ied=Αυτοσχέδιος Εκρηκτικός Μηχανισμός (IED)
insurgency_weapon_c4_ied_desc=Αυτοσχέδια εκρηκτικά με κινητό τηλέφωνο ως πυροκροτητή
insurgency_weapon_f1=χειροβομβίδα F1
insurgency_weapon_f1_desc=Σοβιετική χειροβομβίδα
insurgency_weapon_fal=FAL
insurgency_weapon_galil=Galil
insurgency_weapon_galil_sar=Galil SAR
insurgency_weapon_garand=M-1 GARAND
insurgency_weapon_gp25_smoke=GP-25 Καπνογόνο
insurgency_weapon_gurkha=Khukuri
insurgency_weapon_k98=K-98
insurgency_weapon_kabar=Μαχαίρι
insurgency_weapon_l1a1=L1A1 SLR
insurgency_weapon_m14=M14 EBR
insurgency_weapon_m16=M16A4
insurgency_weapon_m18=Καπνογόνο M18
insurgency_weapon_m18_desc=Καπνογόνο βασικού εξοπλισμού
insurgency_weapon_m1911=M1911
insurgency_weapon_m1911_desc=πιστόλι διαμετρήματος .45 ACP Αμερικανικής προελέυσεως
insurgency_weapon_m1a1=M1 Carbine
insurgency_weapon_m203_he=M203 HE
insurgency_weapon_m203_smoke=M203 Καπνογόνο 
insurgency_weapon_m249=M249
insurgency_weapon_m40a1=M40A1
insurgency_weapon_m45=M45A1
insurgency_weapon_m45_desc=Εκσυγχρονισμένο πιστόλι διαμετρήματος 0.45 ACP Αμερικανικής προελέυσεως
insurgency_weapon_m4a1=M4A1
insurgency_weapon_m590=M590
insurgency_weapon_m67= χειροβομβίδα M67
insurgency_weapon_m84=Χειροβομβίδα Κρότου-Λάμψης M84
insurgency_weapon_m9=M9
insurgency_weapon_makarov=Makarov
insurgency_weapon_mini14=AC-556
insurgency_weapon_mk18=Mk18
insurgency_weapon_model10=Model 10
insurgency_weapon_model10_desc=Ιστορικό  περίστροφο διαμετρήματος 0.38 Αμερικανικής προέλευσης
insurgency_weapon_molotov=Μολότοφ
insurgency_weapon_mosin=Mosin 
insurgency_weapon_mp40=MP40
insurgency_weapon_mp5=MP5K
insurgency_weapon_rpg7=RPG-7
insurgency_weapon_rpk=RPK
insurgency_weapon_sks=SKS
insurgency_weapon_sterling=Sterling
insurgency_weapon_toz=TOZ
insurgency_weapon_ump45=UMP-45
