# Autoimported language for mod insurgency

insurgency_Banned_For_Killing_Teammates=คุณถูกแบนออกจากเซิร์ฟเวอร์เนื่องจากฆ่าเพื่อนร่วมทีมมากเกินไป
insurgency_Compass_E=E
insurgency_Compass_N=N
insurgency_GameUI_ChooseClassTeam=เปลี่ยนทีม
insurgency_GameUI_Coop=ช่วยเหลือกัน
insurgency_GameUI_CustomContent_Tag_CharacterSkin=ลายตัวละคร
insurgency_GameUI_CustomContent_Tag_MapPack=ชุดแผนที่
insurgency_GameUI_CustomContent_Tag_WeaponSkin=ลายอาวุธ
insurgency_GameUI_GameInstructor=คําใบ้การเล่นเกม
insurgency_GameUI_GameSettingsConf=ตั้งค่าเกม
insurgency_GameUI_GamemodeDescription=กฎการปะทะ
insurgency_GameUI_GrenadeAutoSwitch=เปลี่ยนระเบิดอัตโนมัติ
insurgency_GameUI_Main=หน้าหลัก
insurgency_GameUI_ModifyKit=เเต่งอุปกรณ์
insurgency_GameUI_News=ข่าวสาร
insurgency_GameUI_OptionProneAndCrouch=หมอบและนั่งยอง
insurgency_GameUI_Options=ตั้งค่า
insurgency_GameUI_ResumeGame=เล่นต่อ
insurgency_GameUI_SquadOverview=ภาพรวมของทีม
insurgency_GameUI_VipPreference=การตั้งค่าวีไอพี
insurgency_GameUI_vote_changegamemode_skirmish=เปลี่ยนโหมดเกมเป็นการต่อสู้กัน
insurgency_Game_teammate_attack=%s1 โจมตีเพื่อนร่วมทีม (%s2)
insurgency_Game_teammate_kills=ฆ่าเพื่อนร่วมทีม: %s1 ใน %s2
insurgency_Hint_Flashlight=สวมใส่ไฟฉาย
insurgency_Hint_Offline=ฝึกซ้อม (ออฟไลน์)
insurgency_Hint_Online=ภารกิจ (ออนไลน์)
insurgency_Hint_Slide=ขณะที่วิ่ง: สไลด์
insurgency_Hint_ThrowC4=ปา C4
insurgency_Hint_careful_around_teammates=ระวัง!
insurgency_Hint_try_not_to_injure_teammates=พยายามอย่าทำร้ายเพื่อนร่วมทีม
insurgency_INS_end_round_stat_captures=%s2 ได้ทำการยึด %s1
insurgency_INS_end_round_stat_deaths=%s2 ตาย %s1
insurgency_INS_end_round_stat_kills=%s2 ฆ่า %s1
insurgency_KB_Attack=โจมตี
insurgency_KB_ChangeInventory=เปลี่ยนชุดอุปกรณ์
insurgency_KB_ChangeSquad=เปลี่ยนหมู่
insurgency_KB_ChangeStance=เปลี่ยนท่าทาง
insurgency_KB_ChangeTeam=สลับทีม / เปิด,ปิดตารางคะแนน
insurgency_KB_Chat=ข้อความแชท
insurgency_KB_Communications=การสื่อสาร
insurgency_KB_Compass=เข็มทิศ (กดค้าง)
insurgency_KB_CompassToggle=เข็มทิศ (กดเปิด,ปิด)
insurgency_KB_Console=เปิด,ปิด คอนโซล
insurgency_KB_DisplayScoreBoard=แสดงตารางคะแนน
insurgency_KB_DuckHold=นั่ง (กดค้าง)
insurgency_KB_DuckToggle=ย่อตัว(เปิด/ปิด)
insurgency_KB_Firemode=เปลี่ยนโหมดการยิง
insurgency_KB_Flashlight=เปิด/ปิด ไฟฉาย/เลเซอร์
insurgency_KB_Game=เกม
insurgency_KB_Inventory=ช่องเก็บของ
insurgency_KB_Ironsights=ศูนย์เล็ง
insurgency_KB_IronsightsHold=มองศูนย์เล็ง (กดค้าง)
insurgency_KB_IronsightsToggle=มองศูนย์เล็ง (กดเปิด,ปิด)
insurgency_KB_Jump=กระโดด
insurgency_KB_LeanLeft=เอียงซ้าย
insurgency_KB_LeanRight=เอียงขวา
insurgency_KB_Microphone=เปิดไมโครโฟน
insurgency_KB_Misc=อื่นๆ
insurgency_KB_MoveBack=ถอยหลัง
insurgency_KB_MoveForward=เดินหน้า
insurgency_KB_MoveLeft=เดินซ้าย
insurgency_KB_MoveRight=เดินขวา
insurgency_KB_Movement=การเคลื่อนไหว
insurgency_KB_NextWeapon=อาวุธถัดไป
insurgency_KB_PrevWeapon=อาวุธก่อนหน้า
insurgency_KB_Prone=หมอบ
insurgency_KB_Quit=ออก
insurgency_KB_Reload=บรรจุกระสุน
insurgency_KB_Screenshot=ถ่ายภาพหน้าจอ
insurgency_KB_SecondaryGrenade=ขว้างระเบิด
insurgency_KB_SelEquipment=เลือกอุปกรณ์
insurgency_KB_SelKnife=เลือกมีด
insurgency_KB_SelPrimary=เลือกอาวุธหลัก
insurgency_KB_SelSecondary=เลือกอาวุธรอง
insurgency_KB_SelUnderbarrelWeapon=เลือกอาวุธใต้ลำกล้อง
insurgency_KB_Spray=ฉีดสเปร์ยโลโก้
insurgency_KB_Sprint=วิ่ง
insurgency_KB_TacticalMap=แผนที่ยุทธวิธี
insurgency_KB_TeamChat=ข้อความทีม
insurgency_KB_TogglePrimarySecondary=สลับ อาวุธหลัก/อาวุธรอง
insurgency_KB_Use=ใช้สิ่งของ / หยิบอาวุธ
insurgency_KB_UseReload=รีโหลด / ใช้ไอเท็ม / หยิบอาวุธ
insurgency_KB_Walk=เดิน
insurgency_Killed_Teammate=คุณฆ่าเพื่อนร่วมทีม!
insurgency_Msg_Captured=ทำการยึดแล้ว
insurgency_Team_Sec_NATOForces=กองกำลัง NATO
insurgency_Team_Spectators=ผู้ชม
insurgency_death_grenade_c4=C4
insurgency_death_rocket_rpg7=RPG-7
