# Autoimported language for mod insurgency

insurgency_Compass_E=Ö
insurgency_Compass_N=N
insurgency_GameUI_AutoBipod=Automatisk Utvikning Av Gevärsstöd
insurgency_GameUI_ChooseClassTeam=Ändra Lag
insurgency_GameUI_Compete=Tävla
insurgency_GameUI_Coop=Samarbetesläge
insurgency_GameUI_CustomContent_Tag_CharacterSkin=Karaktärs Målningar
insurgency_GameUI_CustomContent_Tag_CustomTheater=Special Theater
insurgency_GameUI_CustomContent_Tag_CustomUI=Special UI
insurgency_GameUI_CustomContent_Tag_MapPack=Ban Paket
insurgency_GameUI_CustomContent_Tag_Misc=Diverse
insurgency_GameUI_CustomContent_Tag_Playlist=Spellista
insurgency_GameUI_CustomContent_Tag_SoundPack=Ljud Paket
insurgency_GameUI_CustomContent_Tag_TotalConversion=Total Omvandling
insurgency_GameUI_CustomContent_Tag_WeaponSkin=Vapenmålningar
insurgency_GameUI_GameInstructor=Speltips
insurgency_GameUI_GameSettingsConf=Spelinställningar
insurgency_GameUI_GameSettingsUseDefaults=Återställ inställningar till deras rekomenderade värden?
insurgency_GameUI_Gamemode=Spelläge
insurgency_GameUI_GamemodeDescription=Anfallsregler
insurgency_GameUI_GrenadeAutoSwitch=Granat auto-byt
insurgency_GameUI_HTMLMOTD=HTML MOTDs
insurgency_GameUI_Help=Hjälp
insurgency_GameUI_Main=Huvudmeny
insurgency_GameUI_ModifyKit=Modifiera Utrustning
insurgency_GameUI_Multiplayer=Flerspelarläge
insurgency_GameUI_News=Nyheter
insurgency_GameUI_OptionAnyStance=Valfri Ställning
insurgency_GameUI_OptionProneAndCrouch=Ligga och Huka
insurgency_GameUI_OptionProneOnly=Ligga Bara
insurgency_GameUI_Options=Inställningar
insurgency_GameUI_Profile=Profil
insurgency_GameUI_ResumeGame=Återuppta Spel
insurgency_GameUI_ServerBrowser=Servervy
insurgency_GameUI_SquadOverview=Truppöversikt
insurgency_GameUI_Translation=Översättning
insurgency_GameUI_UseOpensKit=Använd Tangent Öppnar Kit
insurgency_GameUI_VipPreference=VIP-Preferens
insurgency_GameUI_Workshop=Steam Workshop 
insurgency_GameUI_vote_botcount_checkpoint_0=10 Fiender Per Mål
insurgency_GameUI_vote_botcount_checkpoint_1=15 Fiender Per Mål
insurgency_GameUI_vote_botcount_checkpoint_2=20 Fiender Per Mål
insurgency_GameUI_vote_botcount_checkpoint_3=Normal Fientlig Mängd
insurgency_GameUI_vote_botcount_hunt_0=15 Fiender
insurgency_GameUI_vote_botcount_hunt_1=20 Fiender
insurgency_GameUI_vote_botcount_hunt_2=25 Fiender
insurgency_GameUI_vote_botcount_hunt_3=Normal Fientlig Mängd
insurgency_GameUI_vote_botcount_outpost_0=Förlåtande Fientlig Mängd
insurgency_GameUI_vote_botcount_outpost_1=Normal Fientlig Mängd
insurgency_GameUI_vote_botcount_outpost_2=Oförlåtlig Fientlig Mängd
insurgency_GameUI_vote_botcount_outpost_3=Brutal Fientlig Mängd
insurgency_GameUI_vote_changegamemode_ambush=Byt spelläge till bakhåll?
insurgency_GameUI_vote_changegamemode_battle=Byt spelläge till strid?
insurgency_GameUI_vote_changegamemode_checkpoint=Byt spelläge till kontrollpunkt?
insurgency_GameUI_vote_changegamemode_conquest=Byt spelläge till erövring?
insurgency_GameUI_vote_changegamemode_firefight=Byt spelläge till eldstrid?
insurgency_GameUI_vote_changegamemode_flashpoint=Byt spelläge till flammpunkt?
insurgency_GameUI_vote_changegamemode_hunt=Byt spelläge till jakt?
insurgency_GameUI_vote_changegamemode_infiltrate=Byt spelläge till infiltrering?
insurgency_GameUI_vote_changegamemode_invasion=Byt spelläge till invasion?
insurgency_GameUI_vote_changegamemode_occupy=Byt spelläge till ockupera?
insurgency_GameUI_vote_changegamemode_outpost=Byt spelläge till utpost?
insurgency_GameUI_vote_changegamemode_push=Byt spelläge till på skjutning?
insurgency_GameUI_vote_changegamemode_searchdestroy=Byt spelläge till sök och förstör?
insurgency_GameUI_vote_changegamemode_skirmish=Byt spelläge till skärmytsling?
insurgency_GameUI_vote_changegamemode_strike=Byt spelläget till stöt?
insurgency_GameUI_vote_changegamemode_vendetta=Byt spelläge till vendetta?
insurgency_GameUI_vote_passed_change_ambush=Byter spelläge till bakhåll
insurgency_GameUI_vote_passed_change_battle=Byter spelläge till strid
insurgency_GameUI_vote_passed_change_checkpoint=Byter spelläge till kontrollpunkt
insurgency_GameUI_vote_passed_change_conquest=Byter spelläge till erövring
insurgency_GameUI_vote_passed_change_firefight=Byter spelläge till eldstrid
insurgency_GameUI_vote_passed_change_flashpoint=Byter spelläge till flampunkt
insurgency_GameUI_vote_passed_change_hunt=Byter spelläge till jakt
insurgency_GameUI_vote_passed_change_infiltrate=Byter spelläge till infiltrering
insurgency_GameUI_vote_passed_change_invasion=Byter spelläge till invasion
insurgency_GameUI_vote_passed_change_occupy=Byter spelläge till ockupera
insurgency_GameUI_vote_passed_change_outpost=Byter spelläge till utpost
insurgency_GameUI_vote_passed_change_push=Byter spelläge till påskjutning
insurgency_GameUI_vote_passed_change_searchdestroy=Byter spelläge till sök och förstör
insurgency_GameUI_vote_passed_change_skirmish=Byter spelläge till skärmytsling
insurgency_GameUI_vote_passed_change_strike=Byter spelläge till stöt
insurgency_GameUI_vote_passed_change_vendetta=Byter spelläge till vendetta
insurgency_KB_Attack=Attackera
insurgency_KB_ChangeInventory=Byt Utrustning
insurgency_KB_ChangeSquad=Byt Trupp
insurgency_KB_ChangeStance=Byt Ställning
insurgency_KB_ChangeTeam=Byt Lag/Visa Resultattavla
insurgency_KB_Chat=Chatt Meddelande
insurgency_KB_Combat=Strid
insurgency_KB_Communications=Kommunikation
insurgency_KB_DisplayScoreBoard=Visa Resultattavla
insurgency_KB_DuckHold=Ducka (Håll)
insurgency_KB_DuckToggle=Ducka (på/av)
insurgency_KB_Firemode=Byt Eldgivningsläge
insurgency_KB_Flashlight=Använd Ficklampa / Laser
insurgency_KB_Focus=Fokusera
insurgency_KB_Game=Spel
insurgency_KB_Ironsights=Visirlinje
insurgency_KB_IronsightsHold=Sikta (håll)
insurgency_KB_IronsightsToggle=Sikta (på/av)
insurgency_KB_Jump=Hoppa
insurgency_KB_LeanLeft=Luta Vänster
insurgency_KB_LeanRight=Luta Höger
insurgency_KB_Microphone=Aktivera Mikrofon
insurgency_KB_MoveBack=Gå Bakåt
insurgency_KB_MoveForward=Gå Framåt
insurgency_KB_MoveLeft=Gå Vänster (Åt Sidan)
insurgency_KB_MoveRight=Gå Höger (Åt Sidan)
insurgency_KB_Movement=Rörelse
insurgency_KB_Prone=Ligga
insurgency_KB_Reload=Ladda om
insurgency_KB_SecondaryFire=Sekundär Eldskjutning / Fäll Ut Gevärsstöd
insurgency_KB_SecondaryGrenade=Kasta Granat
insurgency_KB_Sprint=Spring
insurgency_KB_SprintFocusHold=Spring (håll) / Fokusera
insurgency_KB_SprintFocusToggle=Spring (av/på) / Fokusera
insurgency_KB_TacticalMap=Taktisk Karta
insurgency_KB_TeamChat=Lag Meddelande
insurgency_KB_ToggleFloating=Skifta Flytande HUD
insurgency_KB_Use=Använd objekt / Ta upp vapen
insurgency_KB_UseAccessory=Använd Spelares Tillbehör
insurgency_KB_UseReload=Ladda om / Använd objekt / Ta upp vapen
insurgency_KB_Walk=Gå
insurgency_KB_WalkHold=Gå (håll)
insurgency_KB_WalkToggle=Gå (på/av)
insurgency_Msg_ObjectiveWithPrintName=%s1 [%s2]
insurgency_Spec_Binding=[%s1] %s2
insurgency_Spec_ChangeCamera=Byt Kamera
insurgency_Spec_NextPlayer=Nästa Spelare
insurgency_Spec_Outpost=Ditt lag kommer att förstärkas när nästa våg börjar.
insurgency_Spec_PossessBot=Ta över Bot
insurgency_Spec_PreviousPlayer=Förra Spelaren
insurgency_Spec_Survival_Eligible=Ni kommer att förstärkas när en levande lagmedlem når en säker vapengömma.
insurgency_Spec_ToggleXray=Aktivera Röntgen
insurgency_UI_Gamemode=SPELLÄGE
insurgency_UI_Hostname=SERVER NAMN
insurgency_UI_Map=KARTA
insurgency_UI_PlayerCount=SPELARE
insurgency_UI_Scoreboard_Attacking=ATTACKERAR
insurgency_UI_Scoreboard_Defending=FÖRSVARAR
insurgency_UI_Scoreboard_Mute=Blockera Kommunikation
insurgency_UI_Scoreboard_Score=VUNNA RUNDOR: %s1 / POÄNG: %s2
insurgency_UI_Scoreboard_Score_AD=%s1 / VUNNA RUNDOR: %s2 / POÄNG: %s3
insurgency_UI_Scoreboard_Unmute=Tillåt Kommunikation
insurgency_UI_Scoreboard_View_Profile=Se Steam Profil
insurgency_endgamevote_random=Slumpad
insurgency_endgamevote_title=Rösta på nästa bana
insurgency_ins_name_change=* %s1 bytte namn till %s2
insurgency_ins_name_change_limit=* Snälla vänta %s1 sekunder innan du försöker byta namn.
insurgency_prlobby_average_life=Genomsnittlig Livslängd
insurgency_prlobby_casualties=Förluster
insurgency_prlobby_class=Klass
insurgency_prlobby_enemies_suppressed=Undertryckande Eld
insurgency_prlobby_kd=K:D
insurgency_prlobby_kills=Dråp
insurgency_prlobby_location=Plats:
insurgency_prlobby_loser_spaced=F ö r l u s t
insurgency_prlobby_mission=Uppdrag:
insurgency_prlobby_munitions_used=Annat Krigsmateriel
insurgency_prlobby_mvp=Mest Värdefulla Spelare
insurgency_prlobby_obj=Mål
insurgency_prlobby_objectives=Mål
insurgency_prlobby_personal_stats=Personlig Matchstatistik
insurgency_prlobby_preferred_class=Föredragen Klass
insurgency_prlobby_preferred_class_none=Ingen
insurgency_prlobby_roundswon_team1=Säkerhetsstyrkor:
insurgency_prlobby_roundswon_team2=Rebeller:
insurgency_prlobby_score=Poäng
insurgency_prlobby_shots_fired=Skott Avlossade
insurgency_prlobby_team1_stats=Säkerhetsstyrkor
insurgency_prlobby_team2_stats=Rebeller
insurgency_prlobby_tie_spaced=L i k a
insurgency_prlobby_weapon_of_choice=Val av Vapen
insurgency_prlobby_winner_spaced=V i n s t
insurgency_prlobby_winner_spectate=%s1 Vinner
insurgency_radial_affirmative=Uppfattat
insurgency_radial_area_hostile_subtitle=Område fientligt!
insurgency_radial_area_hostile_subtitle_cp=%s1 är fientlig!
insurgency_radial_cease_fire_subtitle=Eldupphör!
insurgency_radial_covering_subtitle=Täcker %s2.
insurgency_radial_covering_subtitle_cp=Täcker %s2 av %s1.
insurgency_radial_enemy_down_subtitle=Fiende nere!
insurgency_radial_enemy_subtitle=Fientlig kontakt, %s2!
insurgency_radial_enemy_subtitle_cp=Fientlig kontakt, %s2 av %s1!
insurgency_radial_flank_left_subtitle=Flankera vänster.
insurgency_radial_flank_right_subtitle=Flankera höger.
insurgency_radial_get_ready_subtitle=Gör redo!
insurgency_radial_go_subtitle=Gå!
insurgency_radial_hold_position_subtitle=Håll position!
insurgency_radial_hold_position_subtitle_cp=Håll positionen vid %s1!
insurgency_radial_move_direction_subtitle=Förflytta %s2!
insurgency_radial_negative=Nekat
insurgency_radial_ontheway_subtitle=På väg.
insurgency_radial_open_fire_subtitle=Öppna eld åt %s2!
insurgency_radial_report_status_subtitle=Statusrapport.
insurgency_radial_stick_together_subtitle=Håll ihop!
insurgency_radial_watch_area_subtitle=Kolla %s2!
insurgency_radial_watch_area_subtitle_cp=Kolla %s2 av %s1!
insurgency_rp_alt_buhriz_coop=Buhriz
insurgency_rp_alt_contact_coop=Kontakt
insurgency_rp_alt_contact_hunt=Kontakt
insurgency_rp_alt_district_coop=Distrikt
insurgency_rp_alt_district_hunt=Distrikt
insurgency_rp_alt_district_survival=Distrikt
insurgency_rp_alt_heights_coop=Höjder
