# Autoimported language for mod insurgency

insurgency_Banned_For_Killing_Teammates=Du har blitt utestengt fra serveren på grunn av du drepte for mange lagspillere.
insurgency_CapturePoint_0=ALFA
insurgency_CapturePoint_1=BRAVO
insurgency_CapturePoint_2=CHARLIE
insurgency_CapturePoint_3=DELTA
insurgency_CapturePoint_4=ECHO
insurgency_CapturePoint_5=FOXTROT
insurgency_CapturePoint_6=GOLF
insurgency_CapturePoint_7=HOTEL
insurgency_CapturePoint_8=INDIA
insurgency_Compass_E=Ø
insurgency_Compass_N=N
insurgency_GameUI_AutoBipod=Auto Stativ-utplassering
insurgency_GameUI_ChooseClassTeam=Bytt Lag
insurgency_GameUI_Compete=konkurrere
insurgency_GameUI_Coop=kooperativ
insurgency_GameUI_CustomContent_Tag_CharacterSkin=Karakterhud
insurgency_GameUI_CustomContent_Tag_CustomTheater=Tilpasset Teater
insurgency_GameUI_CustomContent_Tag_CustomUI=Tilpasset BG
insurgency_GameUI_CustomContent_Tag_MapPack=Kartpakke
insurgency_GameUI_CustomContent_Tag_Misc=Forskjellig
insurgency_GameUI_CustomContent_Tag_Playlist=Spilleliste
insurgency_GameUI_CustomContent_Tag_SoundPack=Lydpakke
insurgency_GameUI_CustomContent_Tag_TotalConversion=Total Omdannelse
insurgency_GameUI_CustomContent_Tag_WeaponSkin=Våpenhud
insurgency_GameUI_GameInstructor=Spillehint
insurgency_GameUI_GameSettingsConf=Spill Innstillinger
insurgency_GameUI_GameSettingsUseDefaults=Restart innstillinger til anbefalte verdier?
insurgency_GameUI_Gamemode=Spillemodus
insurgency_GameUI_GamemodeDescription=Regler for Engasjement
insurgency_GameUI_GrenadeAutoSwitch=Granat Auto-bytte
insurgency_GameUI_HQAnnouncer=HK Annonsør
insurgency_GameUI_HTMLMOTD=HTML MOTDs
insurgency_GameUI_Help=Hjelp
insurgency_GameUI_Main=Hoved
insurgency_GameUI_ModifyKit=Endre Utstyr
insurgency_GameUI_Multiplayer=Flerspiller
insurgency_GameUI_News=Nyheter
insurgency_GameUI_OptionAnyStance=Fri Holdning
insurgency_GameUI_OptionProneAndCrouch=Ligging og Krøking
insurgency_GameUI_OptionProneOnly=Bare Ligging
insurgency_GameUI_Options=Innstillinger
insurgency_GameUI_Profile=Profil
insurgency_GameUI_ResumeGame=Fortsett Spill
insurgency_GameUI_ServerBrowser=Server Liste
insurgency_GameUI_SquadOverview=Troppoversikt
insurgency_GameUI_Training=Trening
insurgency_GameUI_Translation=Oversettelse
insurgency_GameUI_UseOpensKit=Bruk-knapp Åpner Utstyr
insurgency_GameUI_VipPreference=VIP Preferanse
insurgency_GameUI_Workshop=Workshop
insurgency_GameUI_vote_botcount_checkpoint_0=10 Fiender Per Objektiv
insurgency_GameUI_vote_botcount_checkpoint_1=15 Fiender Per Objektiv
insurgency_GameUI_vote_botcount_checkpoint_2=20 Fiender Per Objektiv
insurgency_GameUI_vote_botcount_checkpoint_3=Standard Fiende Telling
insurgency_GameUI_vote_botcount_hunt_0=15 Fiender
insurgency_GameUI_vote_botcount_hunt_1=20 Fiender
insurgency_GameUI_vote_botcount_hunt_2=25 Fiender
insurgency_GameUI_vote_botcount_outpost_0=Tilgivelig Fiende Telling
insurgency_GameUI_vote_botcount_outpost_1=Normal Fiende Telling
insurgency_GameUI_vote_botcount_outpost_2=Utilgivelig Fiende Telling
insurgency_GameUI_vote_botcount_outpost_3=Brutal Fiende Telling
insurgency_GameUI_vote_changegamemode_ambush=Endre spillemodus til ambush?
insurgency_GameUI_vote_changegamemode_battle=Endre spillmodus til slag?
insurgency_GameUI_vote_changegamemode_checkpoint=Endre spillmodus til sjekkpunkt?
insurgency_GameUI_vote_changegamemode_conquest=Endre spillmodus til erobring?
insurgency_GameUI_vote_changegamemode_firefight=Endre spillmodus til skuddveksling?
insurgency_GameUI_vote_changegamemode_flashpoint=Endre spillmodus til flammepunkt?
insurgency_GameUI_vote_changegamemode_hunt=Endre spillmodus til jakt?
insurgency_GameUI_vote_changegamemode_infiltrate=Endre spillemodus til infiltrate?
insurgency_GameUI_vote_changegamemode_invasion=Endre spillmodus til invasjon?
insurgency_GameUI_vote_changegamemode_occupy=Endre spillmodus til okkupere?
insurgency_GameUI_vote_changegamemode_outpost=Endre spillmodus til utpost?
insurgency_GameUI_vote_changegamemode_push=Endre spillmodus til dytt?
insurgency_GameUI_vote_changegamemode_searchdestroy=Endre spillemodus til search and destroy?
insurgency_GameUI_vote_changegamemode_skirmish=Endre spillemodus til skirmish?
insurgency_GameUI_vote_changegamemode_strike=Endre spillemodus til strike?
insurgency_GameUI_vote_changegamemode_vendetta=Endre spillemodus til vendetta?
insurgency_GameUI_vote_passed_change_ambush=Endrer spillmodus til bakhold
insurgency_GameUI_vote_passed_change_battle=Endrer spillmodus til slag
insurgency_GameUI_vote_passed_change_checkpoint=Endrer spillmodus til sjekkpunkt
insurgency_GameUI_vote_passed_change_conquest=Endrer spillmodus til erobring
insurgency_GameUI_vote_passed_change_firefight=Endrer spillmodus til skuddveksling
insurgency_GameUI_vote_passed_change_flashpoint=Endrer spillmodus til flammepunkt
insurgency_GameUI_vote_passed_change_hunt=Endre spillmodus til Jakt
insurgency_GameUI_vote_passed_change_infiltrate=Endrer spillmodus til infiltrere
insurgency_GameUI_vote_passed_change_invasion=Endrer spillmodus til invasjon
insurgency_GameUI_vote_passed_change_occupy=Endrer spillmodus til okkupere
insurgency_GameUI_vote_passed_change_outpost=Endrer spillmodus til utpost
insurgency_GameUI_vote_passed_change_push=Endrer spillmodus til dytt
insurgency_GameUI_vote_passed_change_searchdestroy=Endrer spillmodus til søk og ødelegg
insurgency_GameUI_vote_passed_change_skirmish=Endrer spillmodus til trefning
insurgency_GameUI_vote_passed_change_strike=Endrer spillmodus til angrip
insurgency_Game_idle_kick=%s1 har vert inaktiv for lenge og har blitt sparket.
insurgency_Game_teammate_attack=%s1 angrep en lagspiller (%s2)
insurgency_Game_teammate_kills=Lagspiller drap: %s1 av %s2 
insurgency_Hint_Attachments=Utruste Tilbehør
insurgency_Hint_C4=Utruste C4
insurgency_Hint_Flashlight=Utruste Lommelykt
insurgency_Hint_Focus=Mens du Sikter: Fokus
insurgency_Hint_Frags=Utruste Fragmentgranat
insurgency_Hint_NV=Utruste Natt Syn
insurgency_Hint_Offline=Øv (frakoblet)
insurgency_Hint_Online=Oppdrag (påkoblet)
insurgency_Hint_Plywood=Skyt mål igjennom kryssfiner
insurgency_Hint_Primary=Utruste Primervåpen
insurgency_Hint_ProtectVip=Beskytt VIP!
insurgency_Hint_Slide=Mens du Sprinter: Skli
insurgency_Hint_ThrowC4=Kast C4
insurgency_Hint_ThrowFrag=Kast Fragmentgranat
insurgency_Hint_ToggleCompass=Veksle Kompass
insurgency_Hint_careful_around_teammates=Forsiktig!
insurgency_Hint_tk_punished=Straffet for å ha drept en lagspiller!
insurgency_Hint_try_not_to_injure_teammates=Prøv å ikke skad dine lagspillere.
insurgency_INS_end_round_stat_captures=%s2 fanget %s1
insurgency_INS_end_round_stat_deaths=%s2 dødde %s1
insurgency_INS_end_round_stat_hits=%s2 traff %s1
insurgency_INS_end_round_stat_kills=%s2 drepte %s1
insurgency_INS_end_round_stat_shots=%s2 skøyt %s1
insurgency_KB_Attack=Angrip
insurgency_KB_ChangeInventory=Bytt utstyr
insurgency_KB_ChangeSquad=Bytt tropp
insurgency_KB_ChangeStance=Bytt stanse
insurgency_KB_ChangeTeam=Bytt Lag / Veksle Resultattavle
insurgency_KB_Chat=Sjabbemelding
insurgency_KB_Combat=Kamp
insurgency_KB_Communications=Kommunikasjoner
insurgency_KB_Compass=Kompass (hold)
insurgency_KB_CompassToggle=Kompass (veksle)
insurgency_KB_Console=Veksle Konsoll
insurgency_KB_DisplayScoreBoard=Vis Resultattavle
insurgency_KB_DuckHold=Dukk (hold)
insurgency_KB_DuckToggle=Dukk (veksle)
insurgency_KB_Firemode=Bytt avfyringsmodus
insurgency_KB_Flashlight=Veksle Lykt / Laser
insurgency_KB_Focus=Fokus
insurgency_KB_Game=Spill
insurgency_KB_Inventory=Inventar
insurgency_KB_Ironsights=Standard Sikte
insurgency_KB_IronsightsHold=Sikt Ned Siktet (hold)
insurgency_KB_IronsightsToggle=Sikt Ned Siktet (veksle)
insurgency_KB_Jump=Hopp
insurgency_KB_LeanLeft=Len venstere
insurgency_KB_LeanRight=Len høyre
insurgency_KB_Microphone=Aktiver Mikrofon
insurgency_KB_Misc=Diverse
insurgency_KB_MoveBack=Gå bakover
insurgency_KB_MoveForward=gå fremover
insurgency_KB_MoveLeft=Gå til venstre
insurgency_KB_MoveRight=Gå til høyre
insurgency_KB_Movement=Bevegelse
insurgency_KB_NextWeapon=Neste Våpen
insurgency_KB_PrevWeapon=Forrige Våpen
insurgency_KB_Prone=Legg deg ned
insurgency_KB_Quit=Avslutt
insurgency_KB_RadialMenu=Radial-meny
insurgency_KB_RadialMenuLeader=Radial-meny (leder)
insurgency_KB_RadialMenuOptions=Stemmekommandoer
insurgency_KB_Reload=Lad om
insurgency_KB_Screenshot=Ta Skjermbilde
insurgency_KB_SecondaryFire=Sekundær avfyring / Utplasser Bipod
insurgency_KB_SecondaryGrenade=Kast granat
insurgency_KB_SelEquipment=Velg Utstyr
insurgency_KB_SelKnife=Velg Kniv
insurgency_KB_SelSecondary=Velg Sekundærvåpen
insurgency_KB_SelUnderbarrelWeapon=Velg Underløpvåpen
insurgency_KB_Spray=Spray Logo
insurgency_KB_Sprint=Spurt
insurgency_KB_SprintFocusHold=Løp (hold) / Fokus
insurgency_KB_SprintFocusToggle=Løp (veksle) / Fokus
insurgency_KB_TacticalMap=Taktisk Kart
insurgency_KB_TeamChat=Lagmelding
insurgency_KB_TogglePrimarySecondary=Veksle Primer/Sekundær
insurgency_KB_ToggleRadialMenu=Radial-meny (veksle)
insurgency_KB_ToggleRadialMenuLeader=Radial-meny (veksle, leder)
insurgency_KB_Use=Bruk objekt / Plukk opp våpen
insurgency_KB_UseAccessory=Veksle Spillertilbehør
insurgency_KB_UseReload=Lad om / Bruk element / Plukk opp våpen
insurgency_KB_Walk=Gå
insurgency_KB_WalkHold=Gå (hold)
insurgency_KB_WalkToggle=Gå (veksle)
insurgency_Killed_Teammate=Du drepte en lagspiller!
insurgency_Msg_Captured=fanget
insurgency_Msg_Dominating=%s1 DOMINERE
insurgency_Msg_FlagCapturedEnemy=har fanget vår opplysning
insurgency_Msg_FlagCapturedFriendly=har fanget den fiendlige opplysningen
insurgency_Msg_FlagDroppedEnemy=har mistet opplysningen
insurgency_Msg_FlagDroppedFriendly=har mistet den fiendlige opplysningen
insurgency_Msg_FlagReturnedEnemy=har returnert opplysningen
insurgency_Msg_FlagReturnedFriendly=har returnert vår opplysning
insurgency_Msg_FlagTakenEnemy=har tatt den fiendlige opplysningen
insurgency_Msg_FlagTakenFriendly=har tatt vår opplysning
insurgency_Msg_Neutralized=nøytralisert
insurgency_Msg_ObjectDestroyed=ødelagte objektet
insurgency_Msg_ObjectDestroyedAt=ødelagte objektivet
insurgency_Msg_ObjectiveWeaponCacheDestroyed=ødelagte buffer
insurgency_Msg_ObjectiveWithPrintName=%s1 [%s2]
insurgency_Msg_Revenge=%s1 fikk HEVN på
insurgency_VIP_EscortHint=Eskorter %s1 til sikkerhet!
insurgency_VIP_PreventEscapeHint=Forhindre VIP fra å slippe unna!
insurgency_VIP_YouAreVipHint=Du er VIP. Hold deg til ditt lag!
insurgency_game_description_short_checkpoint=Gå igjennom fiendtlig territorium, klarer områder og hold ut mot fiendtlig mot-angrep.
insurgency_game_description_short_conquer=Gå igjennom fiendtlig territorium, ødelegg våpenbufrer og klarer området.
insurgency_game_description_short_hunt=Lokaliser fiendtlig buffer og eliminer alle opprørere i området.
insurgency_game_description_short_outpost=Hold din grunn for så lenge som mulig.
insurgency_game_description_short_survival=Slåss vekk fiendtlig okkupasjon og overlev så lenge som mulig i denne utfordrende koopmodusen.
insurgency_game_gt_invalid=Ukjent
insurgency_game_gt_normal=Normal
insurgency_game_gt_realism=Realisme
insurgency_playlist_comp=Urangert Konkurranse
insurgency_playlist_comp_desc=5v5 Skuddveksling, fokuserer på balansert spilling.
insurgency_playlist_conquer_coop=Erobre
insurgency_playlist_conquer_coop_desc=Erobre bare på den klassiske instillingen.
insurgency_playlist_coop=Klassisk
insurgency_playlist_coop_desc=Alle moduser bruker standard Insurgency kooperative instillinger.
insurgency_playlist_custom=Tilpasset Servere
insurgency_playlist_custom_desc=Tredje-part servere som bruker modifiserte regler.
insurgency_playlist_elite_coop=Elite
insurgency_playlist_elite_coop_desc=Alle moduser med mer realistisk og taktisk innlasting.
insurgency_playlist_hardcore_coop=Hardkjerna
insurgency_playlist_hardcore_coop_desc=Alle moduser med mer våpen, økt forsyning, og høyere robot-vanskelighetsgrad.
insurgency_playlist_practice=Øvelse mot AI
insurgency_playlist_pvp_sustained=Opprettholdt Kamp
insurgency_playlist_pvp_sustained_desc=Mange forsterkinger, for episk kamp.
insurgency_playlist_pvp_tactical=Taktisk Operasjon
insurgency_playlist_pvp_tactical_desc=Forsterk av objektiv, eller bare et-liv, for høg spenning.
insurgency_playlist_training=Trening
insurgency_playlist_training_desc=Vi sender deg til en fjern forbindelse i Irak for en avansert treningsevaluering.
insurgency_rp_alt_buhriz_coop=Buhriz
insurgency_rp_alt_contact_coop=Kontakt
insurgency_rp_alt_contact_hunt=Kontakt
insurgency_rp_alt_district_coop=Distrikt
insurgency_rp_alt_district_hunt=Distrikt
insurgency_rp_alt_district_survival=Distrikt
insurgency_rp_alt_heights_coop=Høyder
